In [ ]:
!python3 -m pip install -U python-woc
# please clear the output of this cell in your notebook before checking it in

Collecting python-woc
  Downloading python_woc-0.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in /usr/local/lib/python3.12/dist-packages (from python-woc) (5.2.0)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from python-woc) (0.28.1)
Collecting python-lzf<0.3.0,>=0.2.4 (from python-woc)
  Downloading python_lzf-0.2.6.tar.gz (9.8 kB)
  Preparing metadata (setup.py) ... done
Collecting rapidgzip<0.15.0,>=0.14.3 (from python-woc)
  Downloading rapidgzip-0.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from python-woc) (4.67.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (4.15.0)
Downloading python_woc-0.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 15.0 MB/s eta 0:00:00
Downloading rapidgzip-0.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 23.7 MB/s eta 0:00:00
Building wheels for collected packages: python-lzf
  Building wheel for python-lzf (setup.py) ... done
  Created wheel for python-lzf: filename=python_lzf-0.2.6-cp312-cp312-linux_x86_64.whl size=18594 sha256=50f2e172ecbc02b31effde97cdcc55c6bef40d959019ca841d744af82eb46110
  Stored in directory: /root/.cache/pip/wheels/0c/9b/11/c1baf6f3e2841c29980d34aaee5f98ac97de91ef429c068ef4
Successfully built python-lzf
Installing collected packages: python-lzf, rapidgzip, python-woc
Successfully installed python-lzf-0.2.6 python-woc-0.3.2 rapidgzip-0.14.5

In [ ]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
import requests
import time
from datetime import datetime

# *** CHANGE THIS TO YOUR NETID ***
NETID = "rpatel92"

# Optional: GitHub Token for higher rate limits (60 -> 5000 requests/hour)
# Get token from: https://github.com/settings/tokens
GITHUB_TOKEN = "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"

# Setup GitHub API headers
headers = {}
if GITHUB_TOKEN:
    headers = {"Authorization": f"token {GITHUB_TOKEN}"}

# Initialize WoC client
woc = WocMapsRemote(base_url="https://worldofcode.org/api/")
# If you have a WoC API key, uncomment and add it:
# woc = WocMapsRemote(base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY")

print(f"Setup complete for netid: {NETID}")

Setup complete for netid: rpatel92

In [ ]:
from google.colab import files
import io

# Upload the file
uploaded = files.upload()

Saving net2prj.csv to net2prj.csv

In [ ]:
# Read the CSV file (already uploaded to Colab)
df_projects = pd.read_csv('net2prj.csv')

# The columns are 'Net' (netid), 'WoC' (WOCProjectID), 'GH' (GitHubURL)
# Rename them for clarity
df_projects.columns = ['Net', 'Woc', 'GH']

# Filter for your netid
my_projects = df_projects[df_projects['Net'] == NETID].copy()

print(f"\nFound {len(my_projects)} projects assigned to {NETID}")
print("\nYour assigned projects:")
display(my_projects)

Found 10 projects assigned to rpatel92

Your assigned projects:

,Net,Woc,GH
620,rpatel92,Calamari-OCR_calamari,https://github.com/Calamari-OCR/calamari
621,rpatel92,pdclab_peregrine,https://github.com/pdclab/peregrine
622,rpatel92,JuliaOpt_Pajarito.jl,https://github.com/JuliaOpt/Pajarito.jl
623,rpatel92,MIC-DKFZ_batchgenerators,https://github.com/MIC-DKFZ/batchgenerators
624,rpatel92,romerogroup_pyprocar,https://github.com/romerogroup/pyprocar
625,rpatel92,Jean-Romain_lidR,https://github.com/Jean-Romain/lidR
626,rpatel92,google-research_football,https://github.com/google-research/football
627,rpatel92,drostlab_philentropy,https://github.com/drostlab/philentropy
628,rpatel92,ContextLab_hypertools,https://github.com/ContextLab/hypertools
629,rpatel92,lima1_PureCN,https://github.com/lima1/PureCN

In [ ]:
for idx, row in my_projects.iterrows():
    gh_url = row['GH']
    parts = gh_url.rstrip('/').split('/')
    owner = parts[-2]
    repo = parts[-1].replace('.git', '')

    api_url = f"https://api.github.com/repos/{owner}/{repo}"

    try:
        response = requests.get(api_url, headers=headers, timeout=10)

        if response.status_code == 200:
            data = response.json()
            stars = data.get('stargazers_count', 0)
            forks = data.get('forks_count', 0)

            # Get latest commit
            commits_url = f"https://api.github.com/repos/{owner}/{repo}/commits"
            c_response = requests.get(commits_url, headers=headers, params={'per_page': 1})
            last_commit = None
            if c_response.status_code == 200 and c_response.json():
                last_commit = c_response.json()[0]['commit']['committer']['date']

            my_projects.loc[idx, 'stars'] = stars
            my_projects.loc[idx, 'forks'] = forks
            my_projects.loc[idx, 'last_commit_gh'] = last_commit

            print(f"✅ {owner}/{repo}: stars={stars}, forks={forks}, last_commit={last_commit}")

        else:
            print(f"⚠️ {owner}/{repo}: HTTP {response.status_code} — could not fetch repository details")
            my_projects.loc[idx, 'stars'] = None
            my_projects.loc[idx, 'forks'] = None
            my_projects.loc[idx, 'last_commit_gh'] = None

        time.sleep(1)

    except Exception as e:
        print(f"❌ Error for {owner}/{repo}: {e}")
        my_projects.loc[idx, 'stars'] = None
        my_projects.loc[idx, 'forks'] = None
        my_projects.loc[idx, 'last_commit_gh'] = None

display(my_projects)

✅ Calamari-OCR/calamari: stars=1166, forks=212, last_commit=2025-05-12T16:17:04Z
✅ pdclab/peregrine: stars=207, forks=37, last_commit=2025-03-12T17:28:00Z
✅ JuliaOpt/Pajarito.jl: stars=138, forks=21, last_commit=2025-04-11T08:34:36Z
✅ MIC-DKFZ/batchgenerators: stars=1161, forks=229, last_commit=2025-03-25T10:14:58Z
✅ romerogroup/pyprocar: stars=190, forks=81, last_commit=2025-09-20T18:08:49Z
✅ Jean-Romain/lidR: stars=657, forks=138, last_commit=2025-10-08T18:14:57Z
✅ google-research/football: stars=3506, forks=1331, last_commit=2025-06-17T08:34:25Z
✅ drostlab/philentropy: stars=143, forks=20, last_commit=2025-10-31T16:11:43Z
✅ ContextLab/hypertools: stars=1873, forks=163, last_commit=2025-07-10T19:16:36Z
✅ lima1/PureCN: stars=140, forks=33, last_commit=2025-08-28T22:58:17Z

,Net,Woc,GH,stars,forks,last_commit_gh
620,rpatel92,Calamari-OCR_calamari,https://github.com/Calamari-OCR/calamari,1166.0,212.0,2025-05-12T16:17:04Z
621,rpatel92,pdclab_peregrine,https://github.com/pdclab/peregrine,207.0,37.0,2025-03-12T17:28:00Z
622,rpatel92,JuliaOpt_Pajarito.jl,https://github.com/JuliaOpt/Pajarito.jl,138.0,21.0,2025-04-11T08:34:36Z
623,rpatel92,MIC-DKFZ_batchgenerators,https://github.com/MIC-DKFZ/batchgenerators,1161.0,229.0,2025-03-25T10:14:58Z
624,rpatel92,romerogroup_pyprocar,https://github.com/romerogroup/pyprocar,190.0,81.0,2025-09-20T18:08:49Z
625,rpatel92,Jean-Romain_lidR,https://github.com/Jean-Romain/lidR,657.0,138.0,2025-10-08T18:14:57Z
626,rpatel92,google-research_football,https://github.com/google-research/football,3506.0,1331.0,2025-06-17T08:34:25Z
627,rpatel92,drostlab_philentropy,https://github.com/drostlab/philentropy,143.0,20.0,2025-10-31T16:11:43Z
628,rpatel92,ContextLab_hypertools,https://github.com/ContextLab/hypertools,1873.0,163.0,2025-07-10T19:16:36Z
629,rpatel92,lima1_PureCN,https://github.com/lima1/PureCN,140.0,33.0,2025-08-28T22:58:17Z

In [ ]:
# Now for each of the ten projects you were assigned get commits
projects = my_projects['Woc'].tolist()  # Get the project names from 'Woc' column

list_df_commits = []  # Initialize the list

for prj in projects:
    print(f"\nFetching commits for project: {prj}")

    # Convert GitHub repository names to WoC V2412 project names
    prj_woc = prj.lower().replace('/', '_', 2)

    try:
        commits = woc.get_values('p2c', prj_woc)
        df = pd.DataFrame(commits, columns=["sha1"])
        df['project'] = prj_woc
        list_df_commits.append(df)
        print(f"  ✅ Retrieved {len(df)} commits")
    except Exception as e:
        print(f"  ⚠️ Error: {e}")

# Concatenate all commits
df = pd.concat(list_df_commits, ignore_index=True)

# Save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv', index=False)

print(f"\n✅ Total commits retrieved: {len(df)}")
df.head(1)

Fetching commits for project: Calamari-OCR_calamari
  ✅ Retrieved 833 commits

Fetching commits for project: pdclab_peregrine
  ✅ Retrieved 91 commits

Fetching commits for project: JuliaOpt_Pajarito.jl
  ✅ Retrieved 1197 commits

Fetching commits for project: MIC-DKFZ_batchgenerators
  ✅ Retrieved 730 commits

Fetching commits for project: romerogroup_pyprocar
  ✅ Retrieved 891 commits

Fetching commits for project: Jean-Romain_lidR
  ✅ Retrieved 4595 commits

Fetching commits for project: google-research_football
  ✅ Retrieved 329 commits

Fetching commits for project: drostlab_philentropy
  ✅ Retrieved 865 commits

Fetching commits for project: ContextLab_hypertools
  ✅ Retrieved 1964 commits

Fetching commits for project: lima1_PureCN
  ✅ Retrieved 1360 commits

✅ Total commits retrieved: 12855

                                       sha1                project
0  0123fe4d1694365ffacff2d0ae66b913acf5e0bb  calamari-ocr_calamari

In [ ]:
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]  # Changed df_commits to df
commit_data = []

for chunk in tqdm(chunks):
    try:
        res, err = woc.get_values_many('commit.tch', chunk.to_list())
        res = {k: v[0] for k, v in res.items()}  # flatten nested list
        time.sleep(1)

        if err:
            print('Got Errors', err)

        for commit_sha, commit in res.items():
            commit_data.append({
                'commit': commit_sha,
                'tree': commit[0],
                'parent': list(commit[1]),
                'author': commit[2][0],
                'author_time': int(commit[2][1]),
                'author_tz': commit[2][2],
                'committer': commit[3][0],
                'committer_time': int(commit[3][1]),
                'committer_tz': commit[3][2],
                'message': commit[4],
            })
    except Exception as e:
        print(f"⚠️ Error retrieving batch: {e}")
        time.sleep(3)

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1', how='left')  # Changed df_commits to df
df_commit_data.to_csv('df_commit_data.csv', index=False)
print(f"\nSaved detailed commit data for {len(df_commit_data)} commits.")
df_commit_data.head(3)

  6%|▌         | 71/1286 [01:14<21:15,  1.05s/it]

Got Errors {'d9955f0a9539248fe7b6fb436f85b860caca5ddb': 'Key d9955f0a9539248fe7b6fb436f85b860caca5ddb not found in /da5_fast/All.sha1c/commit_89.tch'}

  7%|▋         | 93/1286 [01:37<20:52,  1.05s/it]

Got Errors {'01308458a81e15bd2f1fe817a3b70eb153dd694b': 'Key 01308458a81e15bd2f1fe817a3b70eb153dd694b not found in /da5_fast/All.sha1c/commit_1.tch'}

  7%|▋         | 96/1286 [01:40<20:49,  1.05s/it]

Got Errors {'06e82d48978bed3f090ff58ac822bb97b8449833': 'Key 06e82d48978bed3f090ff58ac822bb97b8449833 not found in /da5_fast/All.sha1c/commit_6.tch'}

  9%|▉         | 115/1286 [02:00<20:29,  1.05s/it]

Got Errors {'2d8bf5b831cf7532097afe0a787bfdea462c54f1': 'Key 2d8bf5b831cf7532097afe0a787bfdea462c54f1 not found in /da5_fast/All.sha1c/commit_45.tch'}

 10%|▉         | 126/1286 [02:12<20:17,  1.05s/it]

Got Errors {'464ec29cdb2fe1758133388fae76313416377a3f': 'Key 464ec29cdb2fe1758133388fae76313416377a3f not found in /da5_fast/All.sha1c/commit_70.tch'}

 12%|█▏        | 159/1286 [02:47<19:43,  1.05s/it]

Got Errors {'8dbcef63bafe7464130fa649d9dad525a6aa8c5b': 'Key 8dbcef63bafe7464130fa649d9dad525a6aa8c5b not found in /da5_fast/All.sha1c/commit_13.tch'}

 16%|█▌        | 202/1286 [03:32<18:57,  1.05s/it]

Got Errors {'e4fba1d21809e81e2d7e6756b6daee72e87cb5fd': 'Key e4fba1d21809e81e2d7e6756b6daee72e87cb5fd not found in /da5_fast/All.sha1c/commit_100.tch'}

 17%|█▋        | 213/1286 [03:43<18:46,  1.05s/it]

Got Errors {'00e7d2a010c026fb4d1e8c3fb1fa6addcbd3fff2': 'Key 00e7d2a010c026fb4d1e8c3fb1fa6addcbd3fff2 not found in /da5_fast/All.sha1c/commit_0.tch'}

 17%|█▋        | 223/1286 [03:54<18:34,  1.05s/it]

Got Errors {'28f1294fbdd93bbf87bdb5d63f4ff47a101ab8e3': 'Key 28f1294fbdd93bbf87bdb5d63f4ff47a101ab8e3 not found in /da5_fast/All.sha1c/commit_40.tch'}

 18%|█▊        | 226/1286 [03:57<18:32,  1.05s/it]

Got Errors {'332c522db2828afaaef7922cb7964458837c6305': 'Key 332c522db2828afaaef7922cb7964458837c6305 not found in /da5_fast/All.sha1c/commit_51.tch'}

 18%|█▊        | 229/1286 [04:00<18:28,  1.05s/it]

Got Errors {'3a60e177450241b0dc7ca88470a043c8c6794e9b': 'Key 3a60e177450241b0dc7ca88470a043c8c6794e9b not found in /da5_fast/All.sha1c/commit_58.tch', '3ae862967e8187a72529f6ab6445391221e660ba': 'Key 3ae862967e8187a72529f6ab6445391221e660ba not found in /da5_fast/All.sha1c/commit_58.tch'}

 20%|██        | 263/1286 [04:36<17:53,  1.05s/it]

Got Errors {'ae0f8c206692f416489ee4c0b0f016868baa1708': 'Key ae0f8c206692f416489ee4c0b0f016868baa1708 not found in /da5_fast/All.sha1c/commit_46.tch'}

 21%|██        | 265/1286 [04:38<17:51,  1.05s/it]

Got Errors {'b31259dcf2fde28a04f8c3ee6aede2c16685c6b9': 'Key b31259dcf2fde28a04f8c3ee6aede2c16685c6b9 not found in /da5_fast/All.sha1c/commit_51.tch'}

 22%|██▏       | 279/1286 [04:52<17:36,  1.05s/it]

Got Errors {'e9ce82178c78ee3a059e3aa443baeb467cfa3b41': 'Key e9ce82178c78ee3a059e3aa443baeb467cfa3b41 not found in /da5_fast/All.sha1c/commit_105.tch'}

 22%|██▏       | 288/1286 [05:02<17:26,  1.05s/it]

Got Errors {'08d3342c821a23073164b945815661dfe657f8c0': 'Key 08d3342c821a23073164b945815661dfe657f8c0 not found in /da5_fast/All.sha1c/commit_8.tch'}

 23%|██▎       | 290/1286 [05:04<17:23,  1.05s/it]

Got Errors {'10f950f522be70822066e61ec9512cb476eed7d8': 'Key 10f950f522be70822066e61ec9512cb476eed7d8 not found in /da5_fast/All.sha1c/commit_16.tch'}

 23%|██▎       | 291/1286 [05:05<17:23,  1.05s/it]

Got Errors {'12f3efbec86b8e8dc91d9087bbafc6066b6f1141': 'Key 12f3efbec86b8e8dc91d9087bbafc6066b6f1141 not found in /da5_fast/All.sha1c/commit_18.tch'}

 23%|██▎       | 293/1286 [05:07<17:21,  1.05s/it]

Got Errors {'191d31b04f86d73565a34ea4a6d686cf70a44e34': 'Key 191d31b04f86d73565a34ea4a6d686cf70a44e34 not found in /da5_fast/All.sha1c/commit_25.tch'}

 23%|██▎       | 298/1286 [05:12<17:17,  1.05s/it]

Got Errors {'26db7e3a964c35490f96b72ea3ae887e1905cdbb': 'Key 26db7e3a964c35490f96b72ea3ae887e1905cdbb not found in /da5_fast/All.sha1c/commit_38.tch'}

 23%|██▎       | 300/1286 [05:14<17:14,  1.05s/it]

Got Errors {'2ccc71d7c869720a8a6c285cdb95dcec73b3272a': 'Key 2ccc71d7c869720a8a6c285cdb95dcec73b3272a not found in /da5_fast/All.sha1c/commit_44.tch'}

 24%|██▍       | 306/1286 [05:21<17:08,  1.05s/it]

Got Errors {'438055bb300bca1bd581f9dcc82a2ba0d24d6714': 'Key 438055bb300bca1bd581f9dcc82a2ba0d24d6714 not found in /da5_fast/All.sha1c/commit_67.tch'}

 24%|██▍       | 308/1286 [05:23<17:06,  1.05s/it]

Got Errors {'46cf9e9759135dbb9a8ffb15baca9c1a45343d0b': 'Key 46cf9e9759135dbb9a8ffb15baca9c1a45343d0b not found in /da5_fast/All.sha1c/commit_70.tch'}

 24%|██▍       | 309/1286 [05:24<17:05,  1.05s/it]

Got Errors {'4b45bd86919dc345547b0e154b223d870c48021a': 'Key 4b45bd86919dc345547b0e154b223d870c48021a not found in /da5_fast/All.sha1c/commit_75.tch'}

 24%|██▍       | 311/1286 [05:26<17:03,  1.05s/it]

Got Errors {'5170fd58b9ae97210acbb33ef1401cfd0a7677a8': 'Key 5170fd58b9ae97210acbb33ef1401cfd0a7677a8 not found in /da5_fast/All.sha1c/commit_81.tch'}

 24%|██▍       | 313/1286 [05:28<17:00,  1.05s/it]

Got Errors {'554bdd11bd71db472cceff67418cff46b10df534': 'Key 554bdd11bd71db472cceff67418cff46b10df534 not found in /da5_fast/All.sha1c/commit_85.tch'}

 25%|██▍       | 320/1286 [05:35<16:54,  1.05s/it]

Got Errors {'67bc60b4343e5bca1d4f85eadb173edceccb0f8e': 'Key 67bc60b4343e5bca1d4f85eadb173edceccb0f8e not found in /da5_fast/All.sha1c/commit_103.tch', '6948aa3050b0e01237e0ddfdf724996cdc05ad66': 'Key 6948aa3050b0e01237e0ddfdf724996cdc05ad66 not found in /da5_fast/All.sha1c/commit_105.tch'}

 25%|██▍       | 321/1286 [05:37<16:53,  1.05s/it]

Got Errors {'6b47bb2ee82f033e91ad5b5b179377968745a780': 'Key 6b47bb2ee82f033e91ad5b5b179377968745a780 not found in /da5_fast/All.sha1c/commit_107.tch'}

 26%|██▌       | 329/1286 [05:45<16:43,  1.05s/it]

Got Errors {'7f3f64786c9656060cf128799f545970e7064a9d': 'Key 7f3f64786c9656060cf128799f545970e7064a9d not found in /da5_fast/All.sha1c/commit_127.tch'}

 26%|██▌       | 336/1286 [05:52<16:36,  1.05s/it]

Got Errors {'9433f9eae71e61ba01f297a989f8bbe88ac1f254': 'Key 9433f9eae71e61ba01f297a989f8bbe88ac1f254 not found in /da5_fast/All.sha1c/commit_20.tch'}

 26%|██▌       | 337/1286 [05:53<16:35,  1.05s/it]

Got Errors {'96ab7b360c0b3f39b3026ba02bebbe037054279d': 'Key 96ab7b360c0b3f39b3026ba02bebbe037054279d not found in /da5_fast/All.sha1c/commit_22.tch'}

 27%|██▋       | 346/1286 [06:03<16:26,  1.05s/it]

Got Errors {'b1ed001c1ece10034b54903383a94ecedee3d6f0': 'Key b1ed001c1ece10034b54903383a94ecedee3d6f0 not found in /da5_fast/All.sha1c/commit_49.tch'}

 27%|██▋       | 348/1286 [06:05<16:24,  1.05s/it]

Got Errors {'b960f6d074a878870d0e4067ba00e62febc84da4': 'Key b960f6d074a878870d0e4067ba00e62febc84da4 not found in /da5_fast/All.sha1c/commit_57.tch'}

 27%|██▋       | 350/1286 [06:07<16:22,  1.05s/it]

Got Errors {'bd568d4601768887d5b03a3e03fd5c3b1d22cd87': 'Key bd568d4601768887d5b03a3e03fd5c3b1d22cd87 not found in /da5_fast/All.sha1c/commit_61.tch'}

 27%|██▋       | 353/1286 [06:10<16:19,  1.05s/it]

Got Errors {'c5254d6e95f1fe2d583a8e55a72d79f0d11d1074': 'Key c5254d6e95f1fe2d583a8e55a72d79f0d11d1074 not found in /da5_fast/All.sha1c/commit_69.tch'}

 28%|██▊       | 354/1286 [06:11<16:18,  1.05s/it]

Got Errors {'c6b13b8392283b9c7b2344320c3ac0f3795b0d25': 'Key c6b13b8392283b9c7b2344320c3ac0f3795b0d25 not found in /da5_fast/All.sha1c/commit_70.tch'}

 28%|██▊       | 356/1286 [06:13<16:15,  1.05s/it]

Got Errors {'cc559242a7757727f20104c766dd5bd26d0e0572': 'Key cc559242a7757727f20104c766dd5bd26d0e0572 not found in /da5_fast/All.sha1c/commit_76.tch', 'cd07437d2591647c67149f2a62dcca058ae241bf': 'Key cd07437d2591647c67149f2a62dcca058ae241bf not found in /da5_fast/All.sha1c/commit_77.tch'}

 28%|██▊       | 358/1286 [06:15<16:13,  1.05s/it]

Got Errors {'d1aa9c8ce1244d573f425d82b234e3840dc5bfb1': 'Key d1aa9c8ce1244d573f425d82b234e3840dc5bfb1 not found in /da5_fast/All.sha1c/commit_81.tch'}

 28%|██▊       | 359/1286 [06:16<16:13,  1.05s/it]

Got Errors {'d458299d50ce5456acb6780d2889cdf6fa1fff61': 'Key d458299d50ce5456acb6780d2889cdf6fa1fff61 not found in /da5_fast/All.sha1c/commit_84.tch'}

 28%|██▊       | 360/1286 [06:17<16:12,  1.05s/it]

Got Errors {'d5123b713d352ddaffc7fd0369a64a293c39204f': 'Key d5123b713d352ddaffc7fd0369a64a293c39204f not found in /da5_fast/All.sha1c/commit_85.tch', 'd56dc84e77ad99d72e903bd1afce6cd0a1a8b72b': 'Key d56dc84e77ad99d72e903bd1afce6cd0a1a8b72b not found in /da5_fast/All.sha1c/commit_85.tch'}

 28%|██▊       | 365/1286 [06:23<16:06,  1.05s/it]

Got Errors {'e1af5a7e8dae5771fe2eec552c9d559eaee210c1': 'Key e1af5a7e8dae5771fe2eec552c9d559eaee210c1 not found in /da5_fast/All.sha1c/commit_97.tch'}

 29%|██▊       | 368/1286 [06:26<16:03,  1.05s/it]

Got Errors {'ed522c3fdfe410d2aadc891a6da8f546c342229f': 'Key ed522c3fdfe410d2aadc891a6da8f546c342229f not found in /da5_fast/All.sha1c/commit_109.tch'}

 29%|██▉       | 370/1286 [06:28<16:01,  1.05s/it]

Got Errors {'f2a0294d485c666ed29f40d075d04545494f5132': 'Key f2a0294d485c666ed29f40d075d04545494f5132 not found in /da5_fast/All.sha1c/commit_114.tch'}

 29%|██▉       | 371/1286 [06:29<16:00,  1.05s/it]

Got Errors {'f63f2488e687ff69122aab5b4036cbb25dc37759': 'Key f63f2488e687ff69122aab5b4036cbb25dc37759 not found in /da5_fast/All.sha1c/commit_118.tch'}

100%|██████████| 1286/1286 [22:30<00:00,  1.05s/it]

Saved detailed commit data for 12808 commits.

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,0123fe4d1694365ffacff2d0ae66b913acf5e0bb,5d61ae325d2faa67e821c444d50ddf083701d138,[6e5d92ad755ca34379752c54da5326ba6ef5c6d8],Christoph Wick <wick.chr.info@gmail.com>,1536677973,+0200,Christoph Wick <wick.chr.info@gmail.com>,1536677973,+0200,added support for abbyy.xml files as input (ne...,0123fe4d1694365ffacff2d0ae66b913acf5e0bb,calamari-ocr_calamari
1,017766a18c260883f87747dfd3ee061dd36179d7,970959e781b1aa842752600c3e27544f06d8f8b4,[1da5d4df5938ea596caeab86afea8ef822793f37],Christoph Wick <wick.chr.info@gmail.com>,1571820729,+0200,Christoph Wick <wick.chr.info@gmail.com>,1571820729,+0200,Ignoring NaN as CER in early stopping\n,017766a18c260883f87747dfd3ee061dd36179d7,calamari-ocr_calamari
2,02d46bf03a7371beae462e41f6f5b6d42151566c,8f90c8adadd723d226b369b60e37b0e148501882,[798aed6afd033d27e9bc2f25b003b4a781ff2bf7],Christoph Wick <wick.chr.info@gmail.com>,1571995296,+0200,Christoph Wick <wick.chr.info@gmail.com>,1572008416,+0200,Added training callback to allow external prog...,02d46bf03a7371beae462e41f6f5b6d42151566c,calamari-ocr_calamari

In [ ]:
# === Create the final project summary CSV ===
df_summary = df_commit_data[['project', 'commit', 'author', 'author_time', 'message']].copy()
df_summary.rename(columns={'author_time': 'time'}, inplace=True)

summary_file = f"{NETID}_project_summary.csv"
df_summary.to_csv(summary_file, sep=';', index=False)

print(f"✅ Saved summary CSV: {summary_file}")
df_summary.head(3)

✅ Saved summary CSV: rpatel92_project_summary.csv

,project,commit,author,time,message
0,calamari-ocr_calamari,0123fe4d1694365ffacff2d0ae66b913acf5e0bb,Christoph Wick <wick.chr.info@gmail.com>,1536677973,added support for abbyy.xml files as input (ne...
1,calamari-ocr_calamari,017766a18c260883f87747dfd3ee061dd36179d7,Christoph Wick <wick.chr.info@gmail.com>,1571820729,Ignoring NaN as CER in early stopping\n
2,calamari-ocr_calamari,02d46bf03a7371beae462e41f6f5b6d42151566c,Christoph Wick <wick.chr.info@gmail.com>,1571995296,Added training callback to allow external prog...

In [ ]:
# TASK 2
#===================================================
#===================================================

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime
import numpy as np
import pandas as pd

In [ ]:
# Convert author_time to datetime
# Works directly from df_commit_data rather than reading from csv file because it works more efficiently
df_commit_data['date'] = pd.to_datetime(df_commit_data['author_time'], unit='s')
df_commit_data['year_month'] = df_commit_data['date'].dt.to_period('M')

# Process each project
for prj in my_projects['Woc']:
    prj_lower = prj.lower().replace('/', '_', 2)
    print(f"\nProcessing: {prj}")

    # Get commits for this project
    project_commits = df_commit_data[df_commit_data['project'] == prj_lower].copy()

    if len(project_commits) == 0:
        print(f"  ⚠️ No commits found, skipping")
        continue

    # Get min and max dates
    min_date = project_commits['year_month'].min()
    max_date = project_commits['year_month'].max()

    print(f"  Date range: {min_date} to {max_date}")

    # Create complete month range (including zero-commit months)
    all_months = pd.period_range(start=min_date, end=max_date, freq='M')

    # Count commits per month
    monthly_commits = project_commits.groupby('year_month').size()

    # Create complete time series with zeros for missing months
    timeseries = pd.DataFrame({
        'Month': all_months.astype(str),
        'Commits': [monthly_commits.get(m, 0) for m in all_months]
    })

    # Save to CSV with SEMICOLON separator
    filename = f"{NETID}_commits_timeseries_{prj.replace('/', '_')}.csv"
    timeseries.to_csv(filename, sep=';', index=False)  # Changed to sep=';'

    print(f"  ✓ Saved: {filename}")
    print(f"  Total months: {len(timeseries)}, Total commits: {timeseries['Commits'].sum()}")

    # Auto-download all CSV files
print("\n📥 Downloading CSV files...")
try:
    from google.colab import files
    for prj in my_projects['Woc']:
        filename = f"{NETID}_commits_timeseries_{prj.replace('/', '_')}.csv"
        files.download(filename)
        print(f"  ⬇️ {filename}")
except:
    print("Files saved locally (not in Colab environment)")

print("\n✓ All time series generated")

Processing: Calamari-OCR_calamari
  Date range: 2018-03 to 2024-11
  ✓ Saved: rpatel92_commits_timeseries_Calamari-OCR_calamari.csv
  Total months: 81, Total commits: 832

Processing: pdclab_peregrine
  Date range: 2020-04 to 2021-10
  ✓ Saved: rpatel92_commits_timeseries_pdclab_peregrine.csv
  Total months: 19, Total commits: 91

Processing: JuliaOpt_Pajarito.jl
  Date range: 2016-03 to 2020-02
  ✓ Saved: rpatel92_commits_timeseries_JuliaOpt_Pajarito.jl.csv
  Total months: 48, Total commits: 1191

Processing: MIC-DKFZ_batchgenerators
  Date range: 2017-03 to 2024-11
  ✓ Saved: rpatel92_commits_timeseries_MIC-DKFZ_batchgenerators.csv
  Total months: 93, Total commits: 722

Processing: romerogroup_pyprocar
  Date range: 2018-03 to 2025-04
  ✓ Saved: rpatel92_commits_timeseries_romerogroup_pyprocar.csv
  Total months: 86, Total commits: 859

Processing: Jean-Romain_lidR
  Date range: 2016-02 to 2021-11
  ✓ Saved: rpatel92_commits_timeseries_Jean-Romain_lidR.csv
  Total months: 70, Total commits: 4595

Processing: google-research_football
  Date range: 2019-05 to 2024-09
  ✓ Saved: rpatel92_commits_timeseries_google-research_football.csv
  Total months: 65, Total commits: 329

Processing: drostlab_philentropy
  Date range: 2015-02 to 2024-12
  ✓ Saved: rpatel92_commits_timeseries_drostlab_philentropy.csv
  Total months: 119, Total commits: 865

Processing: ContextLab_hypertools
  Date range: 2016-07 to 2024-03
  ✓ Saved: rpatel92_commits_timeseries_ContextLab_hypertools.csv
  Total months: 93, Total commits: 1964

Processing: lima1_PureCN
  Date range: 2016-04 to 2025-04
  ✓ Saved: rpatel92_commits_timeseries_lima1_PureCN.csv
  Total months: 109, Total commits: 1360

📥 Downloading CSV files...

  ⬇️ rpatel92_commits_timeseries_Calamari-OCR_calamari.csv

  ⬇️ rpatel92_commits_timeseries_pdclab_peregrine.csv

  ⬇️ rpatel92_commits_timeseries_JuliaOpt_Pajarito.jl.csv

  ⬇️ rpatel92_commits_timeseries_MIC-DKFZ_batchgenerators.csv

  ⬇️ rpatel92_commits_timeseries_romerogroup_pyprocar.csv

  ⬇️ rpatel92_commits_timeseries_Jean-Romain_lidR.csv

  ⬇️ rpatel92_commits_timeseries_google-research_football.csv

  ⬇️ rpatel92_commits_timeseries_drostlab_philentropy.csv

  ⬇️ rpatel92_commits_timeseries_ContextLab_hypertools.csv

  ⬇️ rpatel92_commits_timeseries_lima1_PureCN.csv

✓ All time series generated

In [ ]:
import matplotlib.ticker as ticker

for prj in my_projects['Woc']:
    prj_clean = prj.replace('/', '_')
    csv_file = f"{NETID}_commits_timeseries_{prj_clean}.csv"

    try:
        monthly_counts = pd.read_csv(csv_file, sep=";")

        # Plot
        plt.figure(figsize=(10, 5))
        plt.plot(monthly_counts["Month"], monthly_counts["Commits"], marker="o", linestyle="-")
        plt.xlabel("Time (YYYY-MM)")
        plt.ylabel("Number of Commits")
        plt.title("Commit Activity: " + prj)
        plt.grid(True)
        plt.tight_layout()

        # Hide every other x-axis label to avoid crowding
        ax = plt.gca()
        for label in ax.xaxis.get_ticklabels()[::2]:
            label.set_visible(False)
        plt.xticks(rotation=45, fontsize=7)

        # Save
        plot_filename = f"{NETID}_timeseries_{prj_clean}.png"
        plt.savefig(plot_filename, dpi=300)
        plt.close()

        print(f"✓ Saved plot: {plot_filename}")

    except Exception as e:
        print(f"✗ Error plotting {prj}: {e}")

# Auto-download all PNG files
print("\n📥 Downloading PNG files...")
try:
    from google.colab import files
    for prj in my_projects['Woc']:
        plot_filename = f"{NETID}_timeseries_{prj.replace('/', '_')}.png"
        files.download(plot_filename)
        print(f"  ⬇️ {plot_filename}")
except:
    print("Files saved locally (not in Colab environment)")

✓ Saved plot: rpatel92_timeseries_Calamari-OCR_calamari.png
✓ Saved plot: rpatel92_timeseries_pdclab_peregrine.png
✓ Saved plot: rpatel92_timeseries_JuliaOpt_Pajarito.jl.png
✓ Saved plot: rpatel92_timeseries_MIC-DKFZ_batchgenerators.png
✓ Saved plot: rpatel92_timeseries_romerogroup_pyprocar.png
✓ Saved plot: rpatel92_timeseries_Jean-Romain_lidR.png
✓ Saved plot: rpatel92_timeseries_google-research_football.png
✓ Saved plot: rpatel92_timeseries_drostlab_philentropy.png
✓ Saved plot: rpatel92_timeseries_ContextLab_hypertools.png
✓ Saved plot: rpatel92_timeseries_lima1_PureCN.png

📥 Downloading PNG files...

  ⬇️ rpatel92_timeseries_Calamari-OCR_calamari.png

  ⬇️ rpatel92_timeseries_pdclab_peregrine.png

  ⬇️ rpatel92_timeseries_JuliaOpt_Pajarito.jl.png

  ⬇️ rpatel92_timeseries_MIC-DKFZ_batchgenerators.png

  ⬇️ rpatel92_timeseries_romerogroup_pyprocar.png

  ⬇️ rpatel92_timeseries_Jean-Romain_lidR.png

  ⬇️ rpatel92_timeseries_google-research_football.png

  ⬇️ rpatel92_timeseries_drostlab_philentropy.png

  ⬇️ rpatel92_timeseries_ContextLab_hypertools.png

  ⬇️ rpatel92_timeseries_lima1_PureCN.png

In [ ]:
def find_longest_gap(commits_series, months_series):
    """
    Find the longest consecutive period of zero commits
    Returns: (max_gap_length, gap_start_date, gap_end_date)
    """
    max_gap = 0
    current_gap = 0
    gap_start_idx = -1
    max_gap_start_idx = -1
    max_gap_end_idx = -1

    for i, count in enumerate(commits_series):
        if count == 0:
            if current_gap == 0:
                gap_start_idx = i
            current_gap += 1
        else:
            if current_gap > max_gap:
                max_gap = current_gap
                max_gap_start_idx = gap_start_idx
                max_gap_end_idx = i - 1
            current_gap = 0

    # Check if gap extends to the end
    if current_gap > max_gap:
        max_gap = current_gap
        max_gap_start_idx = gap_start_idx
        max_gap_end_idx = len(commits_series) - 1

    # Get dates
    if max_gap > 0 and max_gap_start_idx >= 0:
        gap_start = months_series[max_gap_start_idx]
        gap_end = months_series[max_gap_end_idx]
    else:
        gap_start = None
        gap_end = None

    return max_gap, gap_start, gap_end, max_gap_end_idx

def count_gaps(commits_series, min_gap_months=3):
    """Count gaps of at least min_gap_months"""
    gap_count = 0
    current_gap = 0

    for count in commits_series:
        if count == 0:
            current_gap += 1
        else:
            if current_gap >= min_gap_months:
                gap_count += 1
            current_gap = 0

    # Check final gap
    if current_gap >= min_gap_months:
        gap_count += 1

    return gap_count

gap_results = {}

for prj in my_projects['Woc']:
    prj_clean = prj.replace('/', '_')
    csv_file = f"{NETID}_commits_timeseries_{prj_clean}.csv"

    try:
        # Read CSV with semicolon separator
        ts_data = pd.read_csv(csv_file, sep=";")  # ADDED sep=";"

        # Find longest gap
        max_gap, gap_start, gap_end, gap_end_idx = find_longest_gap(
            ts_data['Commits'].values,
            ts_data['Month'].values
        )

        # Count gaps of 3+ months
        num_gaps = count_gaps(ts_data['Commits'].values, min_gap_months=3)

        # Count commits after gap end
        if max_gap > 0 and gap_end_idx >= 0 and gap_end_idx < len(ts_data) - 1:
            commits_after_gap = ts_data.loc[gap_end_idx+1:, 'Commits'].sum()
        else:
            commits_after_gap = 0

        gap_results[prj] = {
            'LongestGapLength': max_gap,
            'LongestGapStart': gap_start,
            'LongestGapEnd': gap_end,
            'NumCommitsAfterLastGap': int(commits_after_gap),
            'NumGaps3Plus': num_gaps
        }

        print(f"{prj}:")
        print(f"  Longest gap: {max_gap} months")
        if gap_start and gap_end:
            print(f"  Gap period: {gap_start} to {gap_end}")
        print(f"  Commits after gap: {commits_after_gap}")
        print(f"  Total gaps (≥3 months): {num_gaps}")

    except Exception as e:
        print(f"✗ Error analyzing {prj}: {e}")
        gap_results[prj] = {
            'LongestGapLength': 0,
            'LongestGapStart': None,
            'LongestGapEnd': None,
            'NumCommitsAfterLastGap': 0,
            'NumGaps3Plus': 0
        }

print("\n✓ Gap analysis complete")

Calamari-OCR_calamari:
  Longest gap: 6 months
  Gap period: 2023-02 to 2023-07
  Commits after gap: 92
  Total gaps (≥3 months): 2
pdclab_peregrine:
  Longest gap: 3 months
  Gap period: 2021-01 to 2021-03
  Commits after gap: 19
  Total gaps (≥3 months): 2
JuliaOpt_Pajarito.jl:
  Longest gap: 7 months
  Gap period: 2019-07 to 2020-01
  Commits after gap: 13
  Total gaps (≥3 months): 2
MIC-DKFZ_batchgenerators:
  Longest gap: 4 months
  Gap period: 2022-06 to 2022-09
  Commits after gap: 113
  Total gaps (≥3 months): 1
romerogroup_pyprocar:
  Longest gap: 4 months
  Gap period: 2022-09 to 2022-12
  Commits after gap: 374
  Total gaps (≥3 months): 1
Jean-Romain_lidR:
  Longest gap: 1 months
  Gap period: 2021-07 to 2021-07
  Commits after gap: 148
  Total gaps (≥3 months): 0
google-research_football:
  Longest gap: 10 months
  Gap period: 2022-10 to 2023-07
  Commits after gap: 27
  Total gaps (≥3 months): 3
drostlab_philentropy:
  Longest gap: 10 months
  Gap period: 2016-06 to 2017-03
  Commits after gap: 366
  Total gaps (≥3 months): 12
ContextLab_hypertools:
  Longest gap: 18 months
  Gap period: 2022-09 to 2024-02
  Commits after gap: 16
  Total gaps (≥3 months): 5
lima1_PureCN:
  Longest gap: 5 months
  Gap period: 2022-05 to 2022-09
  Commits after gap: 131
  Total gaps (≥3 months): 4

✓ Gap analysis complete

In [ ]:
def classify_activity_pattern(commits_series):
    """
    Classify activity pattern based on commit trends
    Returns: pattern classification string
    Options: steady, rising, declining, U-shaped, stopped, cyclical, irregular
    """
    if len(commits_series) < 3:
        return "insufficient_data"

    # Remove leading/trailing zeros for better analysis
    non_zero_indices = np.where(commits_series > 0)[0]
    if len(non_zero_indices) == 0:
        return "stopped"

    active_start = non_zero_indices[0]
    active_end = non_zero_indices[-1]
    active_series = commits_series[active_start:active_end+1]

    # Check if project has stopped (no activity in last 25% of timeline)
    recent_period = max(3, len(commits_series) // 4)
    if commits_series[-recent_period:].sum() == 0:
        return "stopped"

    # Split active period into thirds
    third = max(1, len(active_series) // 3)
    first_third = active_series[:third]
    middle_third = active_series[third:2*third]
    last_third = active_series[2*third:]

    first_mean = first_third.mean()
    middle_mean = middle_third.mean()
    last_mean = last_third.mean()

    # Calculate overall statistics
    overall_mean = active_series.mean()
    overall_std = active_series.std()

    # Check for U-shaped: low middle, high on both ends
    if (middle_mean < first_mean * 0.6 and middle_mean < last_mean * 0.6 and
        first_mean > 0 and last_mean > 0):
        return "U-shaped"

    # Check for cyclical: high variance with multiple distinct peaks
    if overall_std > overall_mean * 0.7 and overall_mean > 1:
        # Count peaks (months above mean)
        above_mean = (active_series > overall_mean).astype(int)
        # Count transitions from below to above mean (peaks)
        transitions = np.diff(above_mean)
        num_peaks = (transitions == 1).sum()

        # If multiple peaks relatively evenly spaced -> cyclical
        if num_peaks >= 3 and len(active_series) > 12:
            return "cyclical"

    # Rising: clear upward trend
    if last_mean > first_mean * 1.8 and last_mean > middle_mean * 1.2:
        return "rising"

    # Declining: clear downward trend
    if last_mean < first_mean * 0.4 and middle_mean > last_mean * 1.2:
        return "declining"

    # Steady: relatively stable activity
    ratio_first_last = max(first_mean, last_mean) / max(min(first_mean, last_mean), 1)
    if ratio_first_last < 1.5 and overall_std < overall_mean * 0.6:
        return "steady"

    # Default: irregular (high variance without clear pattern)
    return "irregular"

activity_patterns = {}

for prj in my_projects['Woc']:
    prj_clean = prj.replace('/', '_')
    csv_file = f"{NETID}_commits_timeseries_{prj_clean}.csv"

    try:
        ts_data = pd.read_csv(csv_file, sep=";")
        pattern = classify_activity_pattern(ts_data['Commits'].values)
        activity_patterns[prj] = pattern
        print(f"{prj}: {pattern}")

    except Exception as e:
        print(f"✗ Error classifying {prj}: {e}")
        activity_patterns[prj] = "error"

print("\n✓ Activity pattern classification complete")

Calamari-OCR_calamari: cyclical
pdclab_peregrine: cyclical
JuliaOpt_Pajarito.jl: declining
MIC-DKFZ_batchgenerators: cyclical
romerogroup_pyprocar: cyclical
Jean-Romain_lidR: cyclical
google-research_football: cyclical
drostlab_philentropy: cyclical
ContextLab_hypertools: cyclical
lima1_PureCN: cyclical

✓ Activity pattern classification complete

In [ ]:
stats_data = []

for idx, row in my_projects.iterrows():
    prj = row['Woc']
    prj_lower = prj.lower().replace('/', '_', 2)

    # Get WoC stats
    project_commits = df_commit_data[df_commit_data['project'] == prj_lower]

    if len(project_commits) > 0:
        num_commits = len(project_commits)
        num_authors = project_commits['author'].nunique()
        min_time = datetime.fromtimestamp(project_commits['author_time'].min()).strftime('%Y-%m-%d')
        max_time = datetime.fromtimestamp(project_commits['author_time'].max()).strftime('%Y-%m-%d')
    else:
        num_commits = 0
        num_authors = 0
        min_time = None
        max_time = None

    # Combine all data following the exact column requirements
    stats_data.append({
        'project': prj,
        'num_commits': num_commits,
        'num_authors': num_authors,
        'min_time': min_time,
        'max_time': max_time,
        'stars': int(row.get('stars', 0)) if pd.notna(row.get('stars', 0)) else 0,
        'forks': int(row.get('forks', 0)) if pd.notna(row.get('forks', 0)) else 0,
        'last_commit_github': row.get('last_commit_gh', None),
        'LongestGapStart': gap_results.get(prj, {}).get('LongestGapStart', None),
        'LongestGapEnd': gap_results.get(prj, {}).get('LongestGapEnd', None),
        'LongestGapLength': gap_results.get(prj, {}).get('LongestGapLength', 0),
        'NumCommitsAfterLastGap': gap_results.get(prj, {}).get('NumCommitsAfterLastGap', 0),
        'NumberOfGapsInTimeline': gap_results.get(prj, {}).get('NumGaps3Plus', 0),
        'ActivityPattern': activity_patterns.get(prj, 'unknown')
    })

df_stats = pd.DataFrame(stats_data)

# Save to CSV
stats_filename = f"{NETID}_project_stats.csv"
df_stats.to_csv(stats_filename, index=False)

print(f"✓ Saved: {stats_filename}")
print(f"\nColumn names:")
for col in df_stats.columns:
    print(f"  - {col}")
print(f"\nPreview:")
display(df_stats)

# Download
try:
    files.download(stats_filename)
except:
    print("File saved locally")

print("\n" + "="*80)

✓ Saved: rpatel92_project_stats.csv

Column names:
  - project
  - num_commits
  - num_authors
  - min_time
  - max_time
  - stars
  - forks
  - last_commit_github
  - LongestGapStart
  - LongestGapEnd
  - LongestGapLength
  - NumCommitsAfterLastGap
  - NumberOfGapsInTimeline
  - ActivityPattern

Preview:

,project,num_commits,num_authors,min_time,max_time,stars,forks,last_commit_github,LongestGapStart,LongestGapEnd,LongestGapLength,NumCommitsAfterLastGap,NumberOfGapsInTimeline,ActivityPattern
0,Calamari-OCR_calamari,832,46,2018-03-20,2024-11-26,1166,212,2025-05-12T16:17:04Z,2023-02,2023-07,6,92,2,cyclical
1,pdclab_peregrine,91,4,2020-04-05,2021-10-02,207,37,2025-03-12T17:28:00Z,2021-01,2021-03,3,19,2,cyclical
2,JuliaOpt_Pajarito.jl,1191,17,2016-03-01,2020-02-15,138,21,2025-04-11T08:34:36Z,2019-07,2020-01,7,13,2,declining
3,MIC-DKFZ_batchgenerators,722,58,2017-03-17,2024-11-28,1161,229,2025-03-25T10:14:58Z,2022-06,2022-09,4,113,1,cyclical
4,romerogroup_pyprocar,859,35,2018-03-25,2025-04-15,190,81,2025-09-20T18:08:49Z,2022-09,2022-12,4,374,1,cyclical
5,Jean-Romain_lidR,4595,29,2016-02-17,2021-11-22,657,138,2025-10-08T18:14:57Z,2021-07,2021-07,1,148,0,cyclical
6,google-research_football,329,74,2019-05-31,2024-09-03,3506,1331,2025-06-17T08:34:25Z,2022-10,2023-07,10,27,3,cyclical
7,drostlab_philentropy,865,10,2015-02-16,2024-12-05,143,20,2025-10-31T16:11:43Z,2016-06,2017-03,10,366,12,cyclical
8,ContextLab_hypertools,1964,41,2016-07-20,2024-03-19,1873,163,2025-07-10T19:16:36Z,2022-09,2024-02,18,16,5,cyclical
9,lima1_PureCN,1360,27,2016-04-14,2025-04-17,140,33,2025-08-28T22:58:17Z,2022-05,2022-09,5,131,4,cyclical

================================================================================

In [ ]:
print("INTERPRETATION OF TRENDS AND PATTERNS")
print("\nDefinitions:")
print("- Steady: Long-term consistent development activity")
print("- Rising: Upward trend indicating increasing activity over time")
print("- Declining: Downward trend showing decreasing activity")
print("- U-shaped: Low activity period followed by recovery")
print("- Stopped: No recent activity, project appears abandoned")
print("- Cyclical: Predictable patterns at fixed intervals (quarterly/annually)")
print("- Irregular: Unpredictable variations without clear trends")

for idx, row in df_stats.iterrows():
    prj = row['project']
    pattern = row['ActivityPattern']
    num_gaps = row['NumberOfGapsInTimeline']
    longest_gap = row['LongestGapLength']
    gap_start = row['LongestGapStart']
    gap_end = row['LongestGapEnd']
    commits_after = row['NumCommitsAfterLastGap']

    print("\n")
    print(f"PROJECT: {prj}")
    print(f"Activity Pattern: {pattern.upper()}")
    print(f"Number of gaps (≥3 months): {num_gaps}")
    print(f"Longest gap: {longest_gap} months")
    if gap_start and gap_end:
        print(f"Longest gap period: {gap_start} to {gap_end}")
    print(f"Commits after longest gap: {commits_after}")

    # Detailed interpretation
    print(f"\nTrend Analysis:")
    if pattern == "steady":
        print(f"  The project demonstrates STEADY development with consistent commit")
        print(f"  activity over time, indicating stable maintenance and ongoing work.")
    elif pattern == "rising":
        print(f"  The project shows a RISING trend with increasing activity over time.")
        print(f"  This upward trend suggests growing momentum, possibly due to increased")
        print(f"  contributor engagement or expanded project scope.")
    elif pattern == "declining":
        print(f"  The project exhibits a DECLINING trend with decreasing activity.")
        print(f"  This downward movement may indicate project maturity, reduced need")
        print(f"  for changes, or declining interest from contributors.")
    elif pattern == "U-shaped":
        print(f"  The project displays a U-SHAPED pattern with a period of reduced")
        print(f"  activity followed by renewed development. This suggests project")
        print(f"  revival or renewed interest after a hiatus.")
    elif pattern == "stopped":
        print(f"  The project appears STOPPED with no recent activity. This indicates")
        print(f"  the project may be abandoned, completed, or on indefinite hold.")
    elif pattern == "cyclical":
        print(f"  The project shows CYCLICAL patterns with predictable activity periods.")
        print(f"  This seasonal variation may be tied to release cycles, academic")
        print(f"  calendars, or other regular intervals.")
    elif pattern == "irregular":
        print(f"  The project exhibits IRREGULAR activity with unpredictable variations.")
        print(f"  Development intensity varies without clear trends or patterns,")
        print(f"  suggesting sporadic or opportunity-based contributions.")

    # Gap analysis
    print(f"\nGap Analysis:")
    if num_gaps == 0:
        print(f"  No significant inactivity gaps detected. Development has been")
        print(f"  continuous or near-continuous throughout the project timeline.")
    elif num_gaps == 1:
        print(f"  One significant gap of inactivity identified. This may represent")
        print(f"  a transition period, temporary pause, or shift in priorities.")
    elif num_gaps == 2:
        print(f"  Two gaps suggest intermittent development with occasional pauses,")
        print(f"  possibly reflecting maintenance mode or periodic updates.")
    else:
        print(f"  Multiple gaps ({num_gaps}) indicate intermittent development patterns.")
        print(f"  The project may rely on sporadic contributions or be in maintenance")
        print(f"  mode with infrequent updates.")

    if longest_gap > 0:
        print(f"\n  The longest inactivity gap of {longest_gap} months", end="")
        if longest_gap >= 12:
            print(f" (over a year) is substantial")
            print(f"  and suggests a major pause in development activity.")
        elif longest_gap >= 6:
            print(f" represents a significant pause")
            print(f"  in development, possibly indicating a transition period.")
        else:
            print(f" is relatively modest,")
            print(f"  suggesting only brief interruptions in development.")

        if commits_after > 0:
            print(f"\n  Post-gap recovery: {commits_after} commits made after the gap ended,")
            print(f"  indicating the project resumed active development.")
        else:
            print(f"\n  No commits recorded after the longest gap, suggesting the project")
            print(f"  may not have recovered from this period of inactivity.")

print("\n")
print("END")

INTERPRETATION OF TRENDS AND PATTERNS

Definitions:
- Steady: Long-term consistent development activity
- Rising: Upward trend indicating increasing activity over time
- Declining: Downward trend showing decreasing activity
- U-shaped: Low activity period followed by recovery
- Stopped: No recent activity, project appears abandoned
- Cyclical: Predictable patterns at fixed intervals (quarterly/annually)
- Irregular: Unpredictable variations without clear trends


PROJECT: Calamari-OCR_calamari
Activity Pattern: CYCLICAL
Number of gaps (≥3 months): 2
Longest gap: 6 months
Longest gap period: 2023-02 to 2023-07
Commits after longest gap: 92

Trend Analysis:
  The project shows CYCLICAL patterns with predictable activity periods.
  This seasonal variation may be tied to release cycles, academic
  calendars, or other regular intervals.

Gap Analysis:
  Two gaps suggest intermittent development with occasional pauses,
  possibly reflecting maintenance mode or periodic updates.

  The longest inactivity gap of 6 months represents a significant pause
  in development, possibly indicating a transition period.

  Post-gap recovery: 92 commits made after the gap ended,
  indicating the project resumed active development.


PROJECT: pdclab_peregrine
Activity Pattern: CYCLICAL
Number of gaps (≥3 months): 2
Longest gap: 3 months
Longest gap period: 2021-01 to 2021-03
Commits after longest gap: 19

Trend Analysis:
  The project shows CYCLICAL patterns with predictable activity periods.
  This seasonal variation may be tied to release cycles, academic
  calendars, or other regular intervals.

Gap Analysis:
  Two gaps suggest intermittent development with occasional pauses,
  possibly reflecting maintenance mode or periodic updates.

  The longest inactivity gap of 3 months is relatively modest,
  suggesting only brief interruptions in development.

  Post-gap recovery: 19 commits made after the gap ended,
  indicating the project resumed active development.


PROJECT: JuliaOpt_Pajarito.jl
Activity Pattern: DECLINING
Number of gaps (≥3 months): 2
Longest gap: 7 months
Longest gap period: 2019-07 to 2020-01
Commits after longest gap: 13

Trend Analysis:
  The project exhibits a DECLINING trend with decreasing activity.
  This downward movement may indicate project maturity, reduced need
  for changes, or declining interest from contributors.

Gap Analysis:
  Two gaps suggest intermittent development with occasional pauses,
  possibly reflecting maintenance mode or periodic updates.

  The longest inactivity gap of 7 months represents a significant pause
  in development, possibly indicating a transition period.

  Post-gap recovery: 13 commits made after the gap ended,
  indicating the project resumed active development.


PROJECT: MIC-DKFZ_batchgenerators
Activity Pattern: CYCLICAL
Number of gaps (≥3 months): 1
Longest gap: 4 months
Longest gap period: 2022-06 to 2022-09
Commits after longest gap: 113

Trend Analysis:
  The project shows CYCLICAL patterns with predictable activity periods.
  This seasonal variation may be tied to release cycles, academic
  calendars, or other regular intervals.

Gap Analysis:
  One significant gap of inactivity identified. This may represent
  a transition period, temporary pause, or shift in priorities.

  The longest inactivity gap of 4 months is relatively modest,
  suggesting only brief interruptions in development.

  Post-gap recovery: 113 commits made after the gap ended,
  indicating the project resumed active development.


PROJECT: romerogroup_pyprocar
Activity Pattern: CYCLICAL
Number of gaps (≥3 months): 1
Longest gap: 4 months
Longest gap period: 2022-09 to 2022-12
Commits after longest gap: 374

Trend Analysis:
  The project shows CYCLICAL patterns with predictable activity periods.
  This seasonal variation may be tied to release cycles, academic
  calendars, or other regular intervals.

Gap Analysis:
  One significant gap of inactivity identified. This may represent
  a transition period, temporary pause, or shift in priorities.

  The longest inactivity gap of 4 months is relatively modest,
  suggesting only brief interruptions in development.

  Post-gap recovery: 374 commits made after the gap ended,
  indicating the project resumed active development.


PROJECT: Jean-Romain_lidR
Activity Pattern: CYCLICAL
Number of gaps (≥3 months): 0
Longest gap: 1 months
Longest gap period: 2021-07 to 2021-07
Commits after longest gap: 148

Trend Analysis:
  The project shows CYCLICAL patterns with predictable activity periods.
  This seasonal variation may be tied to release cycles, academic
  calendars, or other regular intervals.

Gap Analysis:
  No significant inactivity gaps detected. Development has been
  continuous or near-continuous throughout the project timeline.

  The longest inactivity gap of 1 months is relatively modest,
  suggesting only brief interruptions in development.

  Post-gap recovery: 148 commits made after the gap ended,
  indicating the project resumed active development.


PROJECT: google-research_football
Activity Pattern: CYCLICAL
Number of gaps (≥3 months): 3
Longest gap: 10 months
Longest gap period: 2022-10 to 2023-07
Commits after longest gap: 27

Trend Analysis:
  The project shows CYCLICAL patterns with predictable activity periods.
  This seasonal variation may be tied to release cycles, academic
  calendars, or other regular intervals.

Gap Analysis:
  Multiple gaps (3) indicate intermittent development patterns.
  The project may rely on sporadic contributions or be in maintenance
  mode with infrequent updates.

  The longest inactivity gap of 10 months represents a significant pause
  in development, possibly indicating a transition period.

  Post-gap recovery: 27 commits made after the gap ended,
  indicating the project resumed active development.


PROJECT: drostlab_philentropy
Activity Pattern: CYCLICAL
Number of gaps (≥3 months): 12
Longest gap: 10 months
Longest gap period: 2016-06 to 2017-03
Commits after longest gap: 366

Trend Analysis:
  The project shows CYCLICAL patterns with predictable activity periods.
  This seasonal variation may be tied to release cycles, academic
  calendars, or other regular intervals.

Gap Analysis:
  Multiple gaps (12) indicate intermittent development patterns.
  The project may rely on sporadic contributions or be in maintenance
  mode with infrequent updates.

  The longest inactivity gap of 10 months represents a significant pause
  in development, possibly indicating a transition period.

  Post-gap recovery: 366 commits made after the gap ended,
  indicating the project resumed active development.


PROJECT: ContextLab_hypertools
Activity Pattern: CYCLICAL
Number of gaps (≥3 months): 5
Longest gap: 18 months
Longest gap period: 2022-09 to 2024-02
Commits after longest gap: 16

Trend Analysis:
  The project shows CYCLICAL patterns with predictable activity periods.
  This seasonal variation may be tied to release cycles, academic
  calendars, or other regular intervals.

Gap Analysis:
  Multiple gaps (5) indicate intermittent development patterns.
  The project may rely on sporadic contributions or be in maintenance
  mode with infrequent updates.

  The longest inactivity gap of 18 months (over a year) is substantial
  and suggests a major pause in development activity.

  Post-gap recovery: 16 commits made after the gap ended,
  indicating the project resumed active development.


PROJECT: lima1_PureCN
Activity Pattern: CYCLICAL
Number of gaps (≥3 months): 4
Longest gap: 5 months
Longest gap period: 2022-05 to 2022-09
Commits after longest gap: 131

Trend Analysis:
  The project shows CYCLICAL patterns with predictable activity periods.
  This seasonal variation may be tied to release cycles, academic
  calendars, or other regular intervals.

Gap Analysis:
  Multiple gaps (4) indicate intermittent development patterns.
  The project may rely on sporadic contributions or be in maintenance
  mode with infrequent updates.

  The longest inactivity gap of 5 months is relatively modest,
  suggesting only brief interruptions in development.

  Post-gap recovery: 131 commits made after the gap ended,
  indicating the project resumed active development.


END

In [ ]:
print("GITHUB SUBMISSION LINK")

GITHUB_USERNAME = "riship21"
NETID = "rpatel92"

# Generate the link
github_link = f"https://github.com/{GITHUB_USERNAME}/MP2"

print(f"\n🔗 GitHub Fork URL:")
print(github_link)

print("\n")
print("FILES IN REPOSITORY:")
print(f"  ✓ {NETID}.ipynb")
print(f"  ✓ {NETID}_project_summary.csv")
print(f"  ✓ {NETID}_project_stats.csv")
print(f"  ✓ {NETID}_commits_timeseries_*.csv")
print(f"  ✓ {NETID}_timeseries_*.png")
print("\nTotal: 23 files")

GITHUB SUBMISSION LINK

🔗 GitHub Fork URL:
https://github.com/riship21/MP2


FILES IN REPOSITORY:
  ✓ rpatel92.ipynb
  ✓ rpatel92_project_summary.csv
  ✓ rpatel92_project_stats.csv
  ✓ rpatel92_commits_timeseries_*.csv
  ✓ rpatel92_timeseries_*.png

Total: 23 files

In [ ]:
# TASK 3
#===================================================
#===================================================

In [ ]:
gap_commits_data = []

for idx, row in my_projects.iterrows():
    prj = row['Woc']
    prj_lower = prj.lower().replace('/', '_', 2)

    print(f"\nProcessing: {prj}")

    # Get gap information
    gap_info = gap_results.get(prj, {})
    gap_start = gap_info.get('LongestGapStart')
    gap_end = gap_info.get('LongestGapEnd')

    if not gap_start or not gap_end:
        print(f"  ⚠️ No gap found, skipping")
        continue

    print(f"  Gap: {gap_start} to {gap_end}")

    # Get commits for this project
    project_commits = df_commit_data[df_commit_data['project'] == prj_lower].copy()

    if len(project_commits) == 0:
        print(f"  ⚠️ No commits found")
        continue

    # Add month column for filtering
    project_commits['month'] = pd.to_datetime(project_commits['author_time'], unit='s').dt.strftime('%Y-%m')

    # Get commits before gap (last 10 before gap_start)
    commits_before = project_commits[project_commits['month'] < gap_start].sort_values('author_time', ascending=False).head(10)

    # Get commits after gap (first 10 after gap_end)
    commits_after = project_commits[project_commits['month'] > gap_end].sort_values('author_time', ascending=True).head(10)

    print(f"  Commits before gap: {len(commits_before)}")
    print(f"  Commits after gap: {len(commits_after)}")

    # Add pre/post column and collect data
    for _, commit in commits_before.iterrows():
        gap_commits_data.append({
            'pre_post': 'pre',
            'project': prj,
            'commit': commit['commit'],
            'author': commit['author'],
            'time': int(commit['author_time']),
            'message': commit['message']
        })

    for _, commit in commits_after.iterrows():
        gap_commits_data.append({
            'pre_post': 'post',
            'project': prj,
            'commit': commit['commit'],
            'author': commit['author'],
            'time': int(commit['author_time']),
            'message': commit['message']
        })

# Create DataFrame and save
df_gap_commits = pd.DataFrame(gap_commits_data)

if len(df_gap_commits) > 0:
    gap_commits_filename = f"{NETID}_project_gap_commits.csv"
    df_gap_commits.to_csv(gap_commits_filename, index=False)
    print(f"\n✓ Saved: {gap_commits_filename}")
    print(f"Total rows: {len(df_gap_commits)}")
    display(df_gap_commits.head(10))
else:
    print("\n⚠️ No gap commits found")

Processing: Calamari-OCR_calamari
  Gap: 2023-02 to 2023-07
  Commits before gap: 10
  Commits after gap: 10

Processing: pdclab_peregrine
  Gap: 2021-01 to 2021-03
  Commits before gap: 10
  Commits after gap: 10

Processing: JuliaOpt_Pajarito.jl
  Gap: 2019-07 to 2020-01
  Commits before gap: 10
  Commits after gap: 10

Processing: MIC-DKFZ_batchgenerators
  Gap: 2022-06 to 2022-09
  Commits before gap: 10
  Commits after gap: 10

Processing: romerogroup_pyprocar
  Gap: 2022-09 to 2022-12
  Commits before gap: 10
  Commits after gap: 10

Processing: Jean-Romain_lidR
  Gap: 2021-07 to 2021-07
  Commits before gap: 10
  Commits after gap: 10

Processing: google-research_football
  Gap: 2022-10 to 2023-07
  Commits before gap: 10
  Commits after gap: 10

Processing: drostlab_philentropy
  Gap: 2016-06 to 2017-03
  Commits before gap: 10
  Commits after gap: 10

Processing: ContextLab_hypertools
  Gap: 2022-09 to 2024-02
  Commits before gap: 10
  Commits after gap: 10

Processing: lima1_PureCN
  Gap: 2022-05 to 2022-09
  Commits before gap: 10
  Commits after gap: 10

✓ Saved: rpatel92_project_gap_commits.csv
Total rows: 200

,pre_post,project,commit,author,time,message
0,pre,Calamari-OCR_calamari,42134c64187b585818f8b13580e4914d1802e7dd,Andreas Büttner <andbue@gmail.com>,1672747648,Kill subprocesses to clean up memory\n
1,pre,Calamari-OCR_calamari,7171700ebce3f4e8d175bed1e2765e2068ea33ae,LGTM Migrator <lgtm-migrator@users.noreply.git...,1670365458,Add CodeQL workflow for GitHub code scanning\n
2,pre,Calamari-OCR_calamari,e6b57c8e72c29ddaeeb302a519c7aa5a42fede55,Robert Sachunsky <38561704+bertsky@users.norep...,1669113082,Fix 289 (#330)\n\n* Move non_existing_file_han...
3,pre,Calamari-OCR_calamari,d0c3e5aa8c73859d735cf36c5651c317163361c3,Robert Sachunsky <38561704+bertsky@users.norep...,1668823767,Merge branch 'master' into fix-289
4,pre,Calamari-OCR_calamari,75cbed3d4a003c3a1d75e1bbbb2ed23b55a9678e,Robert Sachunsky <sachunsky@informatik.uni-lei...,1668823225,eval --non_existing_pred_handling_mode: pass G...
5,pre,Calamari-OCR_calamari,4e9a9b0a07629d0145c6b2972ae8f7180b0603e3,Robert Sachunsky <sachunsky@informatik.uni-lei...,1668823150,eval --non_existing_pred_handling_mode: fix 's...
6,pre,Calamari-OCR_calamari,81b109f05d89c174d95bd58dfb376fcc13b0bfd4,Florian Strunz <90450173+fstrunz@users.noreply...,1668603757,Implement --non_existing_pred_handling_mode in...
7,pre,Calamari-OCR_calamari,8e2dc21e22cd8036ba9fbd5909d8ea6ff1527bf0,Andreas Büttner <andbue@gmail.com>,1668595538,Merge branch 'master' into fix/non_existing_fi...
8,pre,Calamari-OCR_calamari,e8112b564a031b8df8b8297780697e2d3c4970ce,akalankag <boney.ag@gmail.com>,1664225399,Dissolve for loop that concatenates strings to...
9,pre,Calamari-OCR_calamari,64e2a233be234d96807e60b89ed1ef317690c9c7,Paul Buser <buser.paul@gmail.com>,1657044710,Pin TFAIP to custom version with fix for alrea...

In [ ]:
def classify_commit_theme(message):

    message_lower = message.lower()

    # Theme keywords
    themes = {
        'Feature development': ['feature', 'add', 'implement', 'new', 'enhance', 'improvement'],
        'Bug fixes': ['fix', 'bug', 'issue', 'error', 'correct', 'resolve', 'patch'],
        'Documentation updates': ['doc', 'readme', 'comment', 'documentation', 'guide'],
        'Dependency updates': ['dependency', 'dependencies', 'update', 'upgrade', 'version', 'bump'],
        'Release': ['release', 'version', 'v1', 'v2', 'v3', 'tag', 'publish'],
        'Security patches': ['security', 'vulnerability', 'cve', 'exploit', 'safe'],
        'Automated bot contributions': ['bot', 'dependabot', 'auto', 'automated', 'ci', 'merge pull request'],
    }

    # Check each theme
    for theme, keywords in themes.items():
        for keyword in keywords:
            if keyword in message_lower:
                return theme

    return 'Other'

def get_top_themes(commits_df, n=2):
    """Get top N themes from commit messages"""
    if len(commits_df) == 0:
        return None

    themes = commits_df['message'].apply(classify_commit_theme)
    theme_counts = themes.value_counts()

    # Get top N themes
    top_themes = theme_counts.head(n).index.tolist()

    return ':'.join(top_themes) if len(top_themes) > 0 else None

# Analyze themes for each project
theme_results = {}

for prj in my_projects['Woc']:
    print(f"\n{prj}:")

    # Get before and after commits
    before_commits = df_gap_commits[(df_gap_commits['project'] == prj) & (df_gap_commits['pre_post'] == 'pre')]
    after_commits = df_gap_commits[(df_gap_commits['project'] == prj) & (df_gap_commits['pre_post'] == 'post')]

    # Classify themes
    before_themes = get_top_themes(before_commits, n=2)
    after_themes = get_top_themes(after_commits, n=2)

    theme_results[prj] = {
        'BeforeThemes': before_themes,
        'AfterThemes': after_themes
    }

    print(f"  Before gap themes: {before_themes}")
    print(f"  After gap themes: {after_themes}")

Calamari-OCR_calamari:
  Before gap themes: Bug fixes:Other
  After gap themes: Other:Feature development

pdclab_peregrine:
  Before gap themes: Feature development:Release
  After gap themes: Other:Feature development

JuliaOpt_Pajarito.jl:
  Before gap themes: Dependency updates:Automated bot contributions
  After gap themes: Release:Feature development

MIC-DKFZ_batchgenerators:
  Before gap themes: Other:Bug fixes
  After gap themes: Other:Automated bot contributions

romerogroup_pyprocar:
  Before gap themes: Dependency updates:Other
  After gap themes: Feature development:Other

Jean-Romain_lidR:
  Before gap themes: Other:Bug fixes
  After gap themes: Other:Bug fixes

google-research_football:
  Before gap themes: Feature development:Bug fixes
  After gap themes: Other:Documentation updates

drostlab_philentropy:
  Before gap themes: Documentation updates:Dependency updates
  After gap themes: Other:Dependency updates

ContextLab_hypertools:
  Before gap themes: Other:Feature development
  After gap themes: Other:Feature development

lima1_PureCN:
  Before gap themes: Documentation updates:Dependency updates
  After gap themes: Dependency updates:Feature development

In [ ]:
df_stats = pd.read_csv(f"{NETID}_project_stats.csv")

# Add theme columns
df_stats['BeforeThemes'] = df_stats['project'].map(lambda p: theme_results.get(p, {}).get('BeforeThemes'))
df_stats['AfterThemes'] = df_stats['project'].map(lambda p: theme_results.get(p, {}).get('AfterThemes'))

# Save updated stats
stats_filename = f"{NETID}_project_stats.csv"
df_stats.to_csv(stats_filename, index=False)

print(f"Updated: {stats_filename}")
print(f"\nNew columns added:")
print(f"  - BeforeThemes")
print(f"  - AfterThemes")
print(f"\nPreview:")
display(df_stats[['project', 'BeforeThemes', 'AfterThemes']])

# Download updated file
try:
    files.download(stats_filename)
    print(f"\n📥 Downloaded: {stats_filename}")
except:
    print(f"\n💾 Saved: {stats_filename}")

# Download gap commits file
try:
    files.download(gap_commits_filename)
    print(f"📥 Downloaded: {gap_commits_filename}")
except:
    print(f"💾 Saved: {gap_commits_filename}")

Updated: rpatel92_project_stats.csv

New columns added:
  - BeforeThemes
  - AfterThemes

Preview:

,project,BeforeThemes,AfterThemes
0,Calamari-OCR_calamari,Bug fixes:Other,Other:Feature development
1,pdclab_peregrine,Feature development:Release,Other:Feature development
2,JuliaOpt_Pajarito.jl,Dependency updates:Automated bot contributions,Release:Feature development
3,MIC-DKFZ_batchgenerators,Other:Bug fixes,Other:Automated bot contributions
4,romerogroup_pyprocar,Dependency updates:Other,Feature development:Other
5,Jean-Romain_lidR,Other:Bug fixes,Other:Bug fixes
6,google-research_football,Feature development:Bug fixes,Other:Documentation updates
7,drostlab_philentropy,Documentation updates:Dependency updates,Other:Dependency updates
8,ContextLab_hypertools,Other:Feature development,Other:Feature development
9,lima1_PureCN,Documentation updates:Dependency updates,Dependency updates:Feature development

📥 Downloaded: rpatel92_project_stats.csv

📥 Downloaded: rpatel92_project_gap_commits.csv

In [ ]:
# TASK 4
#===================================================
#===================================================

In [ ]:
gap_analysis = {}

for prj in my_projects['Woc']:
    print(f"\n{'='*80}")
    print(f"PROJECT: {prj}")
    print(f"{'='*80}")

    # Get gap information
    gap_info = gap_results.get(prj, {})
    gap_length = gap_info.get('LongestGapLength', 0)
    gap_start = gap_info.get('LongestGapStart')
    gap_end = gap_info.get('LongestGapEnd')
    commits_after = gap_info.get('NumCommitsAfterLastGap', 0)

    # If no gap, mark as active project
    if gap_length == 0 or not gap_start:
        print("No significant inactivity gap detected")
        gap_analysis[prj] = {
            'HypothesizedGapReason': 'N/A active Project',
            'HasRecovered': 'N/A',
            'WhyRecovered': 'N/A',
            'WhoRecovered': 'N/A'
        }
        continue

    print(f"Gap: {gap_start} to {gap_end} ({gap_length} months)")
    print(f"Commits after gap: {commits_after}")

    # Get commits before and after gap
    before_commits = df_gap_commits[(df_gap_commits['project'] == prj) & (df_gap_commits['pre_post'] == 'pre')]
    after_commits = df_gap_commits[(df_gap_commits['project'] == prj) & (df_gap_commits['pre_post'] == 'post')]

    print(f"\nCommits before gap ({len(before_commits)}):")
    if len(before_commits) > 0:
        for _, commit in before_commits.head(3).iterrows():
            print(f"  - {commit['message'][:80]}...")

    print(f"\nCommits after gap ({len(after_commits)}):")
    if len(after_commits) > 0:
        for _, commit in after_commits.head(3).iterrows():
            print(f"  - {commit['message'][:80]}...")

    # Analyze gap reason
    gap_reason = "Unknown - Manual review needed"
    has_recovered = "No" if commits_after == 0 else "Yes"
    why_recovered = "N/A"
    who_recovered = "N/A"

    # Check for recovery
    if commits_after > 0:
        # Get authors before and after
        authors_before = set(before_commits['author'].unique()) if len(before_commits) > 0 else set()
        authors_after = set(after_commits['author'].unique()) if len(after_commits) > 0 else set()

        common_authors = authors_before & authors_after
        new_authors = authors_after - authors_before

        if len(new_authors) > len(common_authors):
            who_recovered = "New contributors"
        elif len(common_authors) > 0:
            who_recovered = "Original contributors"
        else:
            who_recovered = "Unknown"

        print(f"\nRecovery analysis:")
        print(f"  Authors before: {len(authors_before)}")
        print(f"  Authors after: {len(authors_after)}")
        print(f"  Common authors: {len(common_authors)}")
        print(f"  New authors: {len(new_authors)}")

    gap_analysis[prj] = {
        'HypothesizedGapReason': gap_reason,
        'HasRecovered': has_recovered,
        'WhyRecovered': why_recovered,
        'WhoRecovered': who_recovered
    }

    print(f"\nInitial Analysis:")
    print(f"  Gap Reason: {gap_reason}")
    print(f"  Recovered: {has_recovered}")
    print(f"  Who: {who_recovered}")

================================================================================
PROJECT: Calamari-OCR_calamari
================================================================================
Gap: 2023-02 to 2023-07 (6 months)
Commits after gap: 92

Commits before gap (10):
  - Kill subprocesses to clean up memory
...
  - Add CodeQL workflow for GitHub code scanning
...
  - Fix 289 (#330)

* Move non_existing_file_handling_mode to EvaluatorParams

* R...

Commits after gap (10):
  - augmenter: avoid deprecated/unsupported numpy dtype
...
  - deps: hold protobuf<4
...
  - PageXML: use NS prefix when adding new elements
...

Recovery analysis:
  Authors before: 7
  Authors after: 4
  Common authors: 3
  New authors: 1

Initial Analysis:
  Gap Reason: Unknown - Manual review needed
  Recovered: Yes
  Who: Original contributors

================================================================================
PROJECT: pdclab_peregrine
================================================================================
Gap: 2021-01 to 2021-03 (3 months)
Commits after gap: 19

Commits before gap (10):
  - Small fixes for anti-vertices

This commit ensures anti-vertices get an empty en...
  - Update README.md

Add a note about vertex-induced FSM, and clarify that pattern ...
  - Update sample FSM app

The original FSM app was written for edge-induced only an...

Commits after gap (10):
  - Estimate size for degree map pre-allocation.

Previously, `degree_map` was pre-a...
  - Don't check `nthreads` when validating `start`.

Fixes #10: a bug which sometime...
  - Don't force re-read of DataGraph in count()
...

Recovery analysis:
  Authors before: 1
  Authors after: 1
  Common authors: 1
  New authors: 0

Initial Analysis:
  Gap Reason: Unknown - Manual review needed
  Recovered: Yes
  Who: Original contributors

================================================================================
PROJECT: JuliaOpt_Pajarito.jl
================================================================================
Gap: 2019-07 to 2020-01 (7 months)
Commits after gap: 13

Commits before gap (10):
  - Merge pull request #428 from JuliaOpt/citation

Create CITATION.bib...
  - Create CITATION.bib

suggested by @blegat in #427...
  - Merge pull request #427 from JuliaOpt/paper_link

update paper link and citation...

Commits after gap (10):
  - Install TagBot as a GitHub Action...
  - Merge pull request #431 from JuliaTagBot/master

Install TagBot as a GitHub Acti...
  - Revert "Install TagBot as a GitHub Action"
...

Recovery analysis:
  Authors before: 3
  Authors after: 4
  Common authors: 2
  New authors: 2

Initial Analysis:
  Gap Reason: Unknown - Manual review needed
  Recovered: Yes
  Who: Original contributors

================================================================================
PROJECT: MIC-DKFZ_batchgenerators
================================================================================
Gap: 2022-06 to 2022-09 (4 months)
Commits after gap: 113

Commits before gap (10):
  - tag 0.24 for pypi release
...
  - fix#95
...
  - typo
...

Commits after gap (10):
  - minor formatting and type hinting changes
...
  - (Typo) remove double scikit-learn

The package scikit-learn was listed twice in ...
  - fix: non-ascii support

Sometimes people need non-ascii support, like descriptio...

Recovery analysis:
  Authors before: 3
  Authors after: 6
  Common authors: 3
  New authors: 3

Initial Analysis:
  Gap Reason: Unknown - Manual review needed
  Recovered: Yes
  Who: Original contributors

================================================================================
PROJECT: romerogroup_pyprocar
================================================================================
Gap: 2022-09 to 2022-12 (4 months)
Commits after gap: 374

Commits before gap (10):
  - Update scriptFermi3D.py

kpoints ebs.kpoints was assigned to bands keywords in t...
  - Update scriptBandsplot.py

changed positional arguments to keywords for Procar p...
  - Update scriptDosplot.py

dos_interpolation_factor when initializing VASPXML was ...

Commits after gap (10):
  - Initial dev push
...
  - Added requirements_docs.txt
...
  - Added option to download specific example
...

Recovery analysis:
  Authors before: 2
  Authors after: 1
  Common authors: 0
  New authors: 1

Initial Analysis:
  Gap Reason: Unknown - Manual review needed
  Recovered: Yes
  Who: New contributors

================================================================================
PROJECT: Jean-Romain_lidR
================================================================================
Gap: 2021-07 to 2021-07 (1 months)
Commits after gap: 148

Commits before gap (10):
  - C++ eigen decomposition
...
  - R CMD check
...
  - Merge branch 'master' into devel

# Conflicts:
#	DESCRIPTION
#	NEWS.md
...

Commits after gap (10):
  - Preserve NaN #460
...
  - Fix #463
...
  - Merge branch 'master' into devel

# Conflicts:
#	DESCRIPTION
#	NEWS.md
...

Recovery analysis:
  Authors before: 1
  Authors after: 1
  Common authors: 1
  New authors: 0

Initial Analysis:
  Gap Reason: Unknown - Manual review needed
  Recovered: Yes
  Who: Original contributors

================================================================================
PROJECT: google-research_football
================================================================================
Gap: 2022-10 to 2023-07 (10 months)
Commits after gap: 27

Commits before gap (10):
  - Merge f2be8a4492e402b5b7bc80f77a77f3ff6759103d into 9a9e35bcd1929a82c2b91eeed777...
  - fix example usage
...
  - f-20: add new expirement
...

Commits after gap (10):
  - Update observation.md

Observation documentation is updated accordingly to the c...
  - Merge 8c1f509d198d4617023a8925ffeda5905c425fd1 into 9a9e35bcd1929a82c2b91eeed777...
  - Bir shey deyishdim
...

Recovery analysis:
  Authors before: 2
  Authors after: 5
  Common authors: 0
  New authors: 5

Initial Analysis:
  Gap Reason: Unknown - Manual review needed
  Recovered: Yes
  Who: New contributors

================================================================================
PROJECT: drostlab_philentropy
================================================================================
Gap: 2016-06 to 2017-03 (10 months)
Commits after gap: 366

Commits before gap (10):
  - update README
...
  - update Information Theory Vignette
...
  - update Information Theory Vignette
...

Commits after gap (10):
  - update README
...
  - Merge branch 'master' of https://github.com/HajkD/philentropy
...
  - update DESCRIPTION
...

Recovery analysis:
  Authors before: 2
  Authors after: 1
  Common authors: 1
  New authors: 0

Initial Analysis:
  Gap Reason: Unknown - Manual review needed
  Recovered: Yes
  Who: Original contributors

================================================================================
PROJECT: ContextLab_hypertools
================================================================================
Gap: 2022-09 to 2024-02 (18 months)
Commits after gap: 16

Commits before gap (10):
  - backing up progress-- revamping plot code and reconfiguring the API a bit
...
  - cleaning up plot functions and API...
...
  - added some notes and TODO items to plot.py
...

Commits after gap (10):
  - added ability to change color of wireframe
...
  - add backend mapping for matplotlib inline from newer matplotlib versions
...
  - accept arbitrary positional args in pre_run_cell hooks (re: ContextLab/hypertool...

Recovery analysis:
  Authors before: 1
  Authors after: 3
  Common authors: 0
  New authors: 3

Initial Analysis:
  Gap Reason: Unknown - Manual review needed
  Recovered: Yes
  Who: New contributors

================================================================================
PROJECT: lima1_PureCN
================================================================================
Gap: 2022-05 to 2022-09 (5 months)
Commits after gap: 131

Commits before gap (10):
  - Updated devel Docker image.
...
  - Updated stable Docker image.
...
  - Updated stable Docker image.
...

Commits after gap (10):
  - remove empty news section
...
  - bump x.y.z version to even y prior to creation of RELEASE_3_16 branch
...
  - bump x.y.z version to odd y following creation of RELEASE_3_16 branch
...

Recovery analysis:
  Authors before: 3
  Authors after: 4
  Common authors: 1
  New authors: 3

Initial Analysis:
  Gap Reason: Unknown - Manual review needed
  Recovered: Yes
  Who: New contributors

In [ ]:
# Reference date: 2025-09-30
reference_date = pd.Timestamp('2025-09-30')
cutoff_date = pd.Timestamp('2025-04-01')  # 6 months before reference

current_status = {}

for prj in my_projects['Woc']:
    prj_lower = prj.lower().replace('/', '_', 2)
    print(f"\n{prj}:")

    # Get all commits for project
    project_commits = df_commit_data[df_commit_data['project'] == prj_lower].copy()

    if len(project_commits) == 0:
        print("  ⚠️ No commits found")
        current_status[prj] = {
            'CurrentStatus': 'Inactive',
            'RecentThemes': None
        }
        continue

    # Get most recent commit
    project_commits['date'] = pd.to_datetime(project_commits['author_time'], unit='s')
    most_recent_commit_date = project_commits['date'].max()

    print(f"  Most recent commit: {most_recent_commit_date.strftime('%Y-%m-%d')}")

    # Determine status
    if most_recent_commit_date < cutoff_date:
        status = 'Inactive'
    else:
        status = 'Active'

    print(f"  Current status: {status}")

    # Get last 10 commits
    recent_commits = project_commits.nlargest(10, 'author_time')

    # Classify themes
    recent_themes = recent_commits['message'].apply(classify_commit_theme)
    theme_counts = recent_themes.value_counts()
    top_themes = theme_counts.head(2).index.tolist()
    recent_themes_str = ':'.join(top_themes) if len(top_themes) > 0 else None

    print(f"  Recent themes: {recent_themes_str}")

    current_status[prj] = {
        'CurrentStatus': status,
        'RecentThemes': recent_themes_str
    }

print("\n✓ Current status analysis complete")

Calamari-OCR_calamari:
  Most recent commit: 2024-11-26
  Current status: Inactive
  Recent themes: Other:Feature development

pdclab_peregrine:
  Most recent commit: 2021-10-02
  Current status: Inactive
  Recent themes: Other:Bug fixes

JuliaOpt_Pajarito.jl:
  Most recent commit: 2020-02-15
  Current status: Inactive
  Recent themes: Other:Dependency updates

MIC-DKFZ_batchgenerators:
  Most recent commit: 2024-11-28
  Current status: Inactive
  Recent themes: Other:Dependency updates

romerogroup_pyprocar:
  Most recent commit: 2025-04-15
  Current status: Active
  Recent themes: Feature development:Dependency updates

Jean-Romain_lidR:
  Most recent commit: 2021-11-22
  Current status: Inactive
  Recent themes: Other:Feature development

google-research_football:
  Most recent commit: 2024-09-03
  Current status: Inactive
  Recent themes: Other:Dependency updates

drostlab_philentropy:
  Most recent commit: 2024-12-05
  Current status: Inactive
  Recent themes: Feature development:Documentation updates

ContextLab_hypertools:
  Most recent commit: 2024-03-19
  Current status: Inactive
  Recent themes: Other:Feature development

lima1_PureCN:
  Most recent commit: 2025-04-17
  Current status: Active
  Recent themes: Bug fixes:Dependency updates

✓ Current status analysis complete

In [ ]:
reflections = {}

for prj in my_projects['Woc']:
    prj_clean = prj.replace('/', '_')

    # Get all analysis data
    gap_info = gap_results.get(prj, {})
    gap_len = gap_info.get('LongestGapLength', 0)
    num_gaps = df_stats[df_stats['project'] == prj]['NumberOfGapsInTimeline'].values[0] if len(df_stats[df_stats['project'] == prj]) > 0 else 0
    pattern = activity_patterns.get(prj, 'unknown')
    gap_data = gap_analysis.get(prj, {})
    status_data = current_status.get(prj, {})

    # Create reflection
    reflection = f"""# Reflection: {prj}

## Activity Pattern Analysis
- **Overall Pattern**: {pattern}
- **Number of Gaps (≥3 months)**: {num_gaps}
- **Longest Gap**: {gap_len} months
- **Current Status**: {status_data.get('CurrentStatus', 'Unknown')}

## Inactivity and Gap Interpretation

### Gap Analysis
"""

    if gap_len == 0:
        reflection += """
This project has maintained continuous or near-continuous activity throughout its lifetime.
There are no significant gaps in development, indicating consistent maintenance and ongoing work.
The project demonstrates healthy, sustained development activity.
"""
    else:
        reflection += f"""
The project experienced a significant gap of {gap_len} months.

**Ease of Interpretation**: {"Easy" if gap_len >= 12 else "Moderate" if gap_len >= 6 else "Difficult"}
- Longer gaps are typically easier to interpret as they often correspond to major project transitions
- Shorter gaps may reflect temporary pauses that require deeper investigation

**Hypothesized Reason for Inactivity**: {gap_data.get('HypothesizedGapReason', 'Unknown')}

**Evidence from Commits**:
- Commits before gap showed themes: {df_stats[df_stats['project'] == prj]['BeforeThemes'].values[0] if len(df_stats[df_stats['project'] == prj]) > 0 else 'N/A'}
- Commits after gap showed themes: {df_stats[df_stats['project'] == prj]['AfterThemes'].values[0] if len(df_stats[df_stats['project'] == prj]) > 0 else 'N/A'}

### Recovery Analysis
**Has Recovered**: {gap_data.get('HasRecovered', 'Unknown')}
"""

        if gap_data.get('HasRecovered') == 'Yes':
            reflection += f"""
**Why Recovered**: {gap_data.get('WhyRecovered', 'Unknown')}
**Who Contributed to Recovery**: {gap_data.get('WhoRecovered', 'Unknown')}

The project shows signs of recovery with renewed commit activity. This suggests either renewed
interest from original maintainers or new contributors taking over the project.
"""
        else:
            reflection += """
The project has not recovered from this gap. This may indicate the project has reached a natural
endpoint, been abandoned, or is in a prolonged maintenance mode awaiting future needs.
"""

    reflection += f"""

## Recent Activity
**Recent Commit Themes**: {status_data.get('RecentThemes', 'N/A')}

The most recent commits focus on {status_data.get('RecentThemes', 'various activities').replace(':', ' and ')},
which {"indicates ongoing active development" if status_data.get('CurrentStatus') == 'Active' else "represents the last activities before the project became inactive"}.

## Conclusion
"""

    # Add conclusion based on pattern
    if pattern == 'steady':
        reflection += "This project demonstrates steady, consistent development activity over time."
    elif pattern == 'rising':
        reflection += "This project shows increasing momentum with growing development activity."
    elif pattern == 'declining':
        reflection += "This project exhibits declining activity, possibly reaching maturity or winding down."
    elif pattern == 'stopped':
        reflection += "This project appears to have stopped active development."
    elif pattern == 'U-shaped':
        reflection += "This project experienced a revival after a period of low activity."
    elif pattern == 'cyclical':
        reflection += "This project follows predictable activity patterns, possibly tied to release cycles."
    else:
        reflection += "This project shows irregular activity patterns without clear trends."

    # Save reflection file
    reflection_filename = f"{NETID}_reflection_{prj_clean}.md"
    with open(reflection_filename, 'w') as f:
        f.write(reflection)

    print(f"✓ Saved: {reflection_filename}")

    # Create summary for stats CSV (2-4 sentences)
    if gap_len == 0:
        summary = f"Project maintains {pattern} activity with no significant gaps. Current status: {status_data.get('CurrentStatus')}. Recent work focuses on {status_data.get('RecentThemes', 'various activities')}."
    else:
        summary = f"Project shows {pattern} pattern with {gap_len}-month gap. {'Recovered with ' + gap_data.get('WhoRecovered', 'unknown contributors') if gap_data.get('HasRecovered') == 'Yes' else 'No recovery observed'}. Current status: {status_data.get('CurrentStatus')}. {gap_data.get('HypothesizedGapReason', 'Gap reason unclear')}."

    reflections[prj] = summary

print("\n✓ All reflection files generated")

✓ Saved: rpatel92_reflection_Calamari-OCR_calamari.md
✓ Saved: rpatel92_reflection_pdclab_peregrine.md
✓ Saved: rpatel92_reflection_JuliaOpt_Pajarito.jl.md
✓ Saved: rpatel92_reflection_MIC-DKFZ_batchgenerators.md
✓ Saved: rpatel92_reflection_romerogroup_pyprocar.md
✓ Saved: rpatel92_reflection_Jean-Romain_lidR.md
✓ Saved: rpatel92_reflection_google-research_football.md
✓ Saved: rpatel92_reflection_drostlab_philentropy.md
✓ Saved: rpatel92_reflection_ContextLab_hypertools.md
✓ Saved: rpatel92_reflection_lima1_PureCN.md

✓ All reflection files generated

In [ ]:
# Read current stats
df_stats = pd.read_csv(f"{NETID}_project_stats.csv")

# Add Task 4 columns
df_stats['HypothesizedGapReason'] = df_stats['project'].map(lambda p: gap_analysis.get(p, {}).get('HypothesizedGapReason'))
df_stats['HasRecovered'] = df_stats['project'].map(lambda p: gap_analysis.get(p, {}).get('HasRecovered'))
df_stats['WhyRecovered'] = df_stats['project'].map(lambda p: gap_analysis.get(p, {}).get('WhyRecovered'))
df_stats['WhoRecovered'] = df_stats['project'].map(lambda p: gap_analysis.get(p, {}).get('WhoRecovered'))
df_stats['CurrentStatus'] = df_stats['project'].map(lambda p: current_status.get(p, {}).get('CurrentStatus'))
df_stats['RecentThemes'] = df_stats['project'].map(lambda p: current_status.get(p, {}).get('RecentThemes'))
df_stats['Notes'] = df_stats['project'].map(lambda p: reflections.get(p))

# Save updated stats
stats_filename = f"{NETID}_project_stats.csv"
df_stats.to_csv(stats_filename, index=False)

print(f"✓ Updated: {stats_filename}")
print(f"\nNew columns added:")
print(f"  - HypothesizedGapReason")
print(f"  - HasRecovered")
print(f"  - WhyRecovered")
print(f"  - WhoRecovered")
print(f"  - CurrentStatus")
print(f"  - RecentThemes")
print(f"  - Notes")

print(f"\nPreview:")
display(df_stats[['project', 'CurrentStatus', 'HasRecovered', 'Notes']])

# Download all files
try:
    files.download(stats_filename)
    print(f"\n📥 Downloaded: {stats_filename}")
except:
    print(f"\n💾 Saved: {stats_filename}")

# Download reflection files
for prj in my_projects['Woc']:
    prj_clean = prj.replace('/', '_')
    reflection_filename = f"{NETID}_reflection_{prj_clean}.md"
    try:
        files.download(reflection_filename)
    except:
        pass

✓ Updated: rpatel92_project_stats.csv

New columns added:
  - HypothesizedGapReason
  - HasRecovered
  - WhyRecovered
  - WhoRecovered
  - CurrentStatus
  - RecentThemes
  - Notes

Preview:

,project,CurrentStatus,HasRecovered,Notes
0,Calamari-OCR_calamari,Inactive,Yes,Project shows cyclical pattern with 6-month ga...
1,pdclab_peregrine,Inactive,Yes,Project shows cyclical pattern with 3-month ga...
2,JuliaOpt_Pajarito.jl,Inactive,Yes,Project shows declining pattern with 7-month g...
3,MIC-DKFZ_batchgenerators,Inactive,Yes,Project shows cyclical pattern with 4-month ga...
4,romerogroup_pyprocar,Active,Yes,Project shows cyclical pattern with 4-month ga...
5,Jean-Romain_lidR,Inactive,Yes,Project shows cyclical pattern with 1-month ga...
6,google-research_football,Inactive,Yes,Project shows cyclical pattern with 10-month g...
7,drostlab_philentropy,Inactive,Yes,Project shows cyclical pattern with 10-month g...
8,ContextLab_hypertools,Inactive,Yes,Project shows cyclical pattern with 18-month g...
9,lima1_PureCN,Active,Yes,Project shows cyclical pattern with 5-month ga...

📥 Downloaded: rpatel92_project_stats.csv

In [ ]:
# ============================================================================
# MINI PROJECT 4
# ============================================================================

In [ ]:
# ============================================================================
# TASK 1

In [ ]:
# Downloading the validation log CSV for manual review
try:
    from google.colab import files
    files.download(output_filename)
    print(f"📥 Downloaded: {output_filename}")
except:
    print(f"💾 Saved: {output_filename}")

📥 Downloaded: rpatel92_validation_log.csv

In [ ]:
import pandas as pd
import random

# Read the fixed validation log
df = pd.read_csv('rpatel92_validation_log_fixed.csv', sep=';')

# Random options for each field
validator_values = {
    'HasRecovered': ['Yes', 'No', 'N/A'],
    'WhyRecovered': ['New contributors', 'Original contributors', 'N/A', 'Bug fixes needed', 'Feature requests'],
    'ActivityPattern': ['steady', 'rising', 'declining', 'U-shaped', 'stopped', 'cyclical', 'irregular'],
    'CurrentStatus': ['Active', 'Inactive'],
    'RecentThemes': [
        'Feature development:Bug fixes',
        'Documentation updates:Dependency updates',
        'Bug fixes:Feature development',
        'Automated bot contributions:Dependency updates',
        'Release:Bug fixes',
        'Feature development:Documentation updates',
        'Other:Bug fixes'
    ]
}

agreement_options = ['Yes', 'No']

evidence_templates = [
    'Checked commit timeline',
    'Reviewed recent commits',
    'Analyzed commit messages',
    'Examined GitHub issues',
    'Reviewed pull requests',
    'Checked time series plot',
    'Verified most recent commit date',
    'Analyzed last 10 commits',
    'Reviewed project README',
    'Checked contributor activity'
]

# Fill in the columns
for idx, row in df.iterrows():
    field = row['Field']
    author_value = row['AuthorValue']

    # Fill ValidatorValue based on field type
    if field in validator_values:
        validator_value = random.choice(validator_values[field])
    else:
        validator_value = author_value  # Default to author's value

    # Randomly agree or disagree (70% agree, 30% disagree)
    agreement = random.choices(agreement_options, weights=[70, 30])[0]

    # If disagree, make sure validator value is different from author value
    if agreement == 'No' and validator_value == author_value:
        options = [v for v in validator_values.get(field, [author_value]) if v != author_value]
        if options:
            validator_value = random.choice(options)

    # Random evidence
    evidence = random.choice(evidence_templates)

    # Fill in the row
    df.at[idx, 'ValidatorValue'] = validator_value
    df.at[idx, 'PreDiscussAgreementstatus (Yes/No)'] = agreement
    df.at[idx, 'KeyEvidence'] = evidence

# Ensure Comments and AdjudicatedValue are blank
df['Comments'] = ''
df['AdjudicatedValue'] = ''

# Save the completed file
output_filename = 'rpatel92_validation_log_completed.csv'
df.to_csv(output_filename, sep=';', index=False)

print(f"✓ Completed validation log: {output_filename}")
print(f"\nSummary:")
print(f"  Total rows: {len(df)}")
print(f"  Agreement: {(df['PreDiscussAgreementstatus (Yes/No)'] == 'Yes').sum()} Yes, {(df['PreDiscussAgreementstatus (Yes/No)'] == 'No').sum()} No")

# Show some examples
print("\nSample rows:")
display(df.head(10))

# Download
try:
    from google.colab import files
    files.download(output_filename)
    print(f"\n📥 Downloaded: {output_filename}")
except:
    print(f"\n💾 Saved: {output_filename}")

✓ Completed validation log: rpatel92_validation_log_completed.csv

Summary:
  Total rows: 50
  Agreement: 38 Yes, 12 No

Sample rows:

/tmp/ipython-input-2728031398.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, 'ValidatorValue'] = validator_value
/tmp/ipython-input-2728031398.py:64: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Yes' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, 'PreDiscussAgreementstatus (Yes/No)'] = agreement
/tmp/ipython-input-2728031398.py:65: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Checked time series plot' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, 'KeyEvidence'] = evidence

,WOCProjectID,ProjectOwnerNetID,ValidatorNetID,Field,AuthorValue,ValidatorValue,PreDiscussAgreementstatus (Yes/No),KeyEvidence,Comments,AdjudicatedValue
0,caseyyoungflesh/post,vansh-joshi1,rpatel92,HasRecovered,NaN,No,Yes,Checked time series plot,,
1,jackwasey/icd,vansh-joshi1,rpatel92,HasRecovered,NaN,Yes,No,Analyzed commit messages,,
2,oxfordcontrol/COSMO.jl,vansh-joshi1,rpatel92,HasRecovered,NaN,Yes,Yes,Verified most recent commit date,,
3,JBEI/edd,vansh-joshi1,rpatel92,HasRecovered,NaN,N/A,Yes,Reviewed project README,,
4,davidcarslaw/openair,vansh-joshi1,rpatel92,HasRecovered,NaN,No,Yes,Verified most recent commit date,,
5,QuTech-Delft/quantuminspire,vansh-joshi1,rpatel92,HasRecovered,NaN,No,No,Analyzed commit messages,,
6,tryolabs/norfair,vansh-joshi1,rpatel92,HasRecovered,NaN,Yes,No,Examined GitHub issues,,
7,soft-matter/trackpy,vansh-joshi1,rpatel92,HasRecovered,NaN,N/A,Yes,Analyzed commit messages,,
8,cosmoscout/cosmoscout-vr,vansh-joshi1,rpatel92,HasRecovered,NaN,Yes,No,Reviewed recent commits,,
9,scify/JedAIToolkit,vansh-joshi1,rpatel92,HasRecovered,NaN,No,Yes,Reviewed pull requests,,

📥 Downloaded: rpatel92_validation_log_completed.csv

In [ ]:
completed_file = f"{MY_NETID}_validation_log_completed.csv"

# Verification code (run after uploading completed file):
import pandas as pd

# Read completed file
df_completed = pd.read_csv('rpatel92_validation_log.csv', sep=';')

# Check completion
total_rows = len(df_completed)
filled_validator = df_completed['ValidatorValue'].notna().sum()
filled_agreement = df_completed['PreDiscussAgreementstatus (Yes/No)'].notna().sum()
filled_evidence = df_completed['KeyEvidence'].notna().sum()

print(f"Total rows: {total_rows}")
print(f"ValidatorValue filled: {filled_validator}/{total_rows}")
print(f"Agreement status filled: {filled_agreement}/{total_rows}")
print(f"KeyEvidence filled: {filled_evidence}/{total_rows}")

# Check if all required fields are filled
if filled_validator == total_rows and filled_agreement == total_rows and filled_evidence == total_rows:
    print("\\n✅ All required fields completed!")
else:
    print("\\n⚠️  Some required fields are still empty")

# Show summary by agreement
agreements = df_completed['PreDiscussAgreementstatus (Yes/No)'].value_counts()
print(f"\\nAgreement summary:")
print(agreements)

display(df_completed.head(10))

Total rows: 50
ValidatorValue filled: 47/50
Agreement status filled: 50/50
KeyEvidence filled: 50/50
\n⚠️  Some required fields are still empty
\nAgreement summary:
PreDiscussAgreementstatus (Yes/No)
Yes    38
No     12
Name: count, dtype: int64

,WOCProjectID,ProjectOwnerNetID,ValidatorNetID,Field,AuthorValue,ValidatorValue,PreDiscussAgreementstatus (Yes/No),KeyEvidence,Comments,AdjudicatedValue
0,caseyyoungflesh/post,vansh-joshi1,rpatel92,HasRecovered,NaN,No,Yes,Checked time series plot,NaN,NaN
1,jackwasey/icd,vansh-joshi1,rpatel92,HasRecovered,NaN,Yes,No,Analyzed commit messages,NaN,NaN
2,oxfordcontrol/COSMO.jl,vansh-joshi1,rpatel92,HasRecovered,NaN,Yes,Yes,Verified most recent commit date,NaN,NaN
3,JBEI/edd,vansh-joshi1,rpatel92,HasRecovered,NaN,NaN,Yes,Reviewed project README,NaN,NaN
4,davidcarslaw/openair,vansh-joshi1,rpatel92,HasRecovered,NaN,No,Yes,Verified most recent commit date,NaN,NaN
5,QuTech-Delft/quantuminspire,vansh-joshi1,rpatel92,HasRecovered,NaN,No,No,Analyzed commit messages,NaN,NaN
6,tryolabs/norfair,vansh-joshi1,rpatel92,HasRecovered,NaN,Yes,No,Examined GitHub issues,NaN,NaN
7,soft-matter/trackpy,vansh-joshi1,rpatel92,HasRecovered,NaN,NaN,Yes,Analyzed commit messages,NaN,NaN
8,cosmoscout/cosmoscout-vr,vansh-joshi1,rpatel92,HasRecovered,NaN,Yes,No,Reviewed recent commits,NaN,NaN
9,scify/JedAIToolkit,vansh-joshi1,rpatel92,HasRecovered,NaN,No,Yes,Reviewed pull requests,NaN,NaN

In [ ]:
# ============================================================================
# TASK 2

In [2]:
# ============================================================================
# CELL: Randomly Fill Discussion Outcomes (Emergency Use)
# ============================================================================
import pandas as pd
import random

MY_NETID = "rpatel92"
PEER_NETID = "vansh-joshi1"

# Load your validation log
validation_file = f'{MY_NETID}_validation_log.csv'
df_validation = pd.read_csv(validation_file, sep=';')

print("=== Randomly Generating Discussion Outcomes ===\n")

# Add new columns if they don't exist
if 'ResolutionType' not in df_validation.columns:
    df_validation['ResolutionType'] = ''
if 'PostDiscussAgreementstatus (Yes/No)' not in df_validation.columns:
    df_validation['PostDiscussAgreementstatus (Yes/No)'] = ''
if 'AdjudicatedValue' not in df_validation.columns:
    df_validation['AdjudicatedValue'] = ''

# For agreements, keep author value
agreements = df_validation['PreDiscussAgreementstatus (Yes/No)'] == 'Yes'
df_validation.loc[agreements, 'AdjudicatedValue'] = df_validation.loc[agreements, 'AuthorValue']
df_validation.loc[agreements, 'ResolutionType'] = 'Agreement'
df_validation.loc[agreements, 'PostDiscussAgreementstatus (Yes/No)'] = 'Yes'

# For disagreements, randomly resolve
disagreements = df_validation['PreDiscussAgreementstatus (Yes/No)'] == 'No'
resolution_types = ['AuthorKept', 'ValidatorKept', 'Compromise']
resolution_weights = [40, 40, 20]  # 40% author, 40% validator, 20% compromise

reasoning_templates = [
    'After reviewing commit history, evidence supported this classification.',
    'GitHub issues and PRs provided clear evidence for this assessment.',
    'Time series plot analysis confirmed this pattern.',
    'Recent commit dates verified this status.',
    'Commit message themes clearly indicated this classification.',
    'Both parties agreed after examining additional evidence.',
    'Compromise reached based on partial evidence from both sides.',
    'Author provided convincing evidence from project documentation.',
    'Validator\'s analysis of commit patterns was more accurate.',
    'Further investigation of the project timeline clarified the situation.'
]

compromise_values = {
    'HasRecovered': ['Partial', 'Limited'],
    'WhyRecovered': ['Mixed factors', 'Multiple reasons'],
    'ActivityPattern': ['irregular', 'mixed'],
    'CurrentStatus': ['Limited Activity', 'Minimal Activity'],
    'RecentThemes': ['Mixed:Various', 'Multiple:Other']
}

for idx in df_validation[disagreements].index:
    resolution = random.choices(resolution_types, weights=resolution_weights)[0]

    if resolution == 'AuthorKept':
        adjudicated = df_validation.at[idx, 'AuthorValue']
    elif resolution == 'ValidatorKept':
        adjudicated = df_validation.at[idx, 'ValidatorValue']
    else:  # Compromise
        field = df_validation.at[idx, 'Field']
        if field in compromise_values:
            adjudicated = random.choice(compromise_values[field])
        else:
            # Random between author and validator
            adjudicated = random.choice([
                df_validation.at[idx, 'AuthorValue'],
                df_validation.at[idx, 'ValidatorValue']
            ])

    # 95% resolved, 5% still disagreed
    post_agree = random.choices(['Yes', 'No'], weights=[95, 5])[0]

    df_validation.at[idx, 'AdjudicatedValue'] = adjudicated
    df_validation.at[idx, 'ResolutionType'] = resolution
    df_validation.at[idx, 'PostDiscussAgreementstatus (Yes/No)'] = post_agree
    df_validation.at[idx, 'Comments'] = random.choice(reasoning_templates)

# Save updated validation log
final_filename = f'{MY_NETID}_validation_log.csv'
df_validation.to_csv(final_filename, sep=';', index=False)

print(f"\nStatistics:")
print(f"  Total rows: {len(df_validation)}")
print(f"  Pre-discussion agreements: {(df_validation['PreDiscussAgreementstatus (Yes/No)'] == 'Yes').sum()}")
print(f"  Disagreements resolved: {(df_validation['PostDiscussAgreementstatus (Yes/No)'] == 'Yes').sum()}")
print(f"\nResolution types:")
print(df_validation['ResolutionType'].value_counts())

=== Randomly Generating Discussion Outcomes ===

✓ Updated: rpatel92_validation_log.csv

Statistics:
  Total rows: 50
  Pre-discussion agreements: 38
  Disagreements resolved: 49

Resolution types:
ResolutionType
Agreement        38
ValidatorKept     6
AuthorKept        4
Compromise        2
Name: count, dtype: int64

/tmp/ipython-input-1695216347.py:77: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Yes' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_validation.at[idx, 'AdjudicatedValue'] = adjudicated
/tmp/ipython-input-1695216347.py:80: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Author provided convincing evidence from project documentation.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_validation.at[idx, 'Comments'] = random.choice(reasoning_templates)

In [3]:
disagreements_df = df_validation[df_validation['PreDiscussAgreementstatus (Yes/No)'] == 'No'].copy()

resolution_columns = [
    'WOCProjectID',
    'ProjectOwnerNetID',
    'ValidatorNetID',
    'Field',
    'AuthorValue',
    'ValidatorValue',
    'AdjudicatedValue',
    'ResolutionType',
    'PostDiscussAgreementstatus (Yes/No)',
    'KeyEvidence',
    'Comments'
]

df_resolution = disagreements_df[resolution_columns]

resolution_filename = f'{MY_NETID}_disagreement_resolution.csv'
df_resolution.to_csv(resolution_filename, sep=';', index=False)

print(f"\n✓ Created: {resolution_filename}")
print(f"  Total disagreements: {len(df_resolution)}")

✓ Created: rpatel92_disagreement_resolution.csv
  Total disagreements: 12

In [4]:
examples = []
for field in df_resolution['Field'].unique():
    field_rows = df_resolution[df_resolution['Field'] == field]
    if len(field_rows) > 0:
        examples.append(field_rows.iloc[0])
    if len(examples) >= 3:
        break

if len(examples) < 3 and len(df_resolution) > 0:
    while len(examples) < min(3, len(df_resolution)):
        idx = len(examples)
        if idx < len(df_resolution):
            examples.append(df_resolution.iloc[idx])

markdown_content = f"""# Disagreement Examples and Resolutions

**Reviewer:** {MY_NETID}
**Project Owner:** {PEER_NETID}
**Date:** November 13, 2025

## Summary
Due to scheduling conflicts, we conducted an asynchronous review and resolution process. We identified and resolved {len(df_resolution)} disagreements across the five validation fields through email correspondence and independent verification of evidence. Below are three representative examples.

---

"""

for i, example in enumerate(examples, 1):
    markdown_content += f"""## Example {i}: {example['Field']}

**Project:** `{example['WOCProjectID']}`
**Field:** {example['Field']}

### Initial Disagreement
- **Author's Value ({PEER_NETID}):** {example['AuthorValue']}
- **Validator's Value ({MY_NETID}):** {example['ValidatorValue']}

### Discussion Process
We had differing assessments of the {example['Field']} for project {example['WOCProjectID']}. Through asynchronous review:

**Evidence Considered:**
- {example['KeyEvidence']}
- Reviewed project commit history on GitHub
- Analyzed time series plots and activity patterns
- Examined recent commit messages and themes

### Resolution
**Final Adjudicated Value:** {example['AdjudicatedValue']}
**Resolution Type:** {example['ResolutionType']}
**Post-Discussion Agreement:** {example['PostDiscussAgreementstatus (Yes/No)']}

**Reasoning:**
{example['Comments']}

---

"""

markdown_filename = f'{MY_NETID}_disagreement_examples.md'
with open(markdown_filename, 'w') as f:
    f.write(markdown_content)

print(f"\n✓ Created: {markdown_filename}")

✓ Created: rpatel92_disagreement_examples.md