In [3]:
!python3 -m pip install -U python-woc
# please clear the output of this cell in your notebook before checking it in

Collecting python-woc
  Downloading python_woc-0.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in /usr/local/lib/python3.12/dist-packages (from python-woc) (5.2.0)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from python-woc) (0.28.1)
Collecting python-lzf<0.3.0,>=0.2.4 (from python-woc)
  Downloading python_lzf-0.2.6.tar.gz (9.8 kB)
  Preparing metadata (setup.py) ... done
Collecting rapidgzip<0.15.0,>=0.14.3 (from python-woc)
  Downloading rapidgzip-0.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from python-woc) (4.67.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.28.1->python-woc) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (4.15.0)
Downloading python_woc-0.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 70.2 MB/s eta 0:00:00
Downloading rapidgzip-0.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 77.0 MB/s eta 0:00:00
Building wheels for collected packages: python-lzf
  Building wheel for python-lzf (setup.py) ... done
  Created wheel for python-lzf: filename=python_lzf-0.2.6-cp312-cp312-linux_x86_64.whl size=18592 sha256=ec7d2bc34adc23a4a0a1ecbce6a75acc9026f2c0babc41f280993a63c3e9f341
  Stored in directory: /root/.cache/pip/wheels/0c/9b/11/c1baf6f3e2841c29980d34aaee5f98ac97de91ef429c068ef4
Successfully built python-lzf
Installing collected packages: python-lzf, rapidgzip, python-woc
Successfully installed python-lzf-0.2.6 python-woc-0.3.2 rapidgzip-0.14.5

In [4]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
import requests
import time
from datetime import datetime

# *** CHANGE THIS TO YOUR NETID ***
NETID = "rpatel92"

# Optional: GitHub Token for higher rate limits (60 -> 5000 requests/hour)
# Get token from: https://github.com/settings/tokens
GITHUB_TOKEN = "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"

# Setup GitHub API headers
headers = {}
if GITHUB_TOKEN:
    headers = {"Authorization": f"token {GITHUB_TOKEN}"}

# Initialize WoC client
woc = WocMapsRemote(base_url="https://worldofcode.org/api/")
# If you have a WoC API key, uncomment and add it:
# woc = WocMapsRemote(base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY")

print(f"Setup complete for netid: {NETID}")

Setup complete for netid: rpatel92

In [5]:
from google.colab import files
import io

# Upload the file
uploaded = files.upload()

Saving net2prj.csv to net2prj.csv

In [6]:
# Read the CSV file (already uploaded to Colab)
df_projects = pd.read_csv('net2prj.csv')

# The columns are 'Net' (netid), 'WoC' (WOCProjectID), 'GH' (GitHubURL)
# Rename them for clarity
df_projects.columns = ['Net', 'Woc', 'GH']

# Filter for your netid
my_projects = df_projects[df_projects['Net'] == NETID].copy()

print(f"\nFound {len(my_projects)} projects assigned to {NETID}")
print("\nYour assigned projects:")
display(my_projects)

Found 10 projects assigned to rpatel92

Your assigned projects:

,Net,Woc,GH
620,rpatel92,Calamari-OCR_calamari,https://github.com/Calamari-OCR/calamari
621,rpatel92,pdclab_peregrine,https://github.com/pdclab/peregrine
622,rpatel92,JuliaOpt_Pajarito.jl,https://github.com/JuliaOpt/Pajarito.jl
623,rpatel92,MIC-DKFZ_batchgenerators,https://github.com/MIC-DKFZ/batchgenerators
624,rpatel92,romerogroup_pyprocar,https://github.com/romerogroup/pyprocar
625,rpatel92,Jean-Romain_lidR,https://github.com/Jean-Romain/lidR
626,rpatel92,google-research_football,https://github.com/google-research/football
627,rpatel92,drostlab_philentropy,https://github.com/drostlab/philentropy
628,rpatel92,ContextLab_hypertools,https://github.com/ContextLab/hypertools
629,rpatel92,lima1_PureCN,https://github.com/lima1/PureCN

In [7]:
print("\n=== Getting GitHub Stats (with error handling) ===\n")

for idx, row in my_projects.iterrows():
    gh_url = row['GH']
    parts = gh_url.rstrip('/').split('/')
    owner = parts[-2]
    repo = parts[-1].replace('.git', '')

    api_url = f"https://api.github.com/repos/{owner}/{repo}"

    try:
        response = requests.get(api_url, headers=headers, timeout=10)

        if response.status_code == 200:
            data = response.json()
            stars = data.get('stargazers_count', 0)
            forks = data.get('forks_count', 0)

            # Get latest commit
            commits_url = f"https://api.github.com/repos/{owner}/{repo}/commits"
            c_response = requests.get(commits_url, headers=headers, params={'per_page': 1})
            last_commit = None
            if c_response.status_code == 200 and c_response.json():
                last_commit = c_response.json()[0]['commit']['committer']['date']

            my_projects.loc[idx, 'stars'] = stars
            my_projects.loc[idx, 'forks'] = forks
            my_projects.loc[idx, 'last_commit_gh'] = last_commit

            print(f"✅ {owner}/{repo}: stars={stars}, forks={forks}, last_commit={last_commit}")

        else:
            print(f"⚠️ {owner}/{repo}: HTTP {response.status_code} — could not fetch repository details")
            my_projects.loc[idx, 'stars'] = None
            my_projects.loc[idx, 'forks'] = None
            my_projects.loc[idx, 'last_commit_gh'] = None

        time.sleep(1)

    except Exception as e:
        print(f"❌ Error for {owner}/{repo}: {e}")
        my_projects.loc[idx, 'stars'] = None
        my_projects.loc[idx, 'forks'] = None
        my_projects.loc[idx, 'last_commit_gh'] = None

display(my_projects)

=== Getting GitHub Stats (with error handling) ===

✅ Calamari-OCR/calamari: stars=1165, forks=212, last_commit=2025-05-12T16:17:04Z
✅ pdclab/peregrine: stars=207, forks=37, last_commit=2025-03-12T17:28:00Z
✅ JuliaOpt/Pajarito.jl: stars=138, forks=21, last_commit=2025-04-11T08:34:36Z
✅ MIC-DKFZ/batchgenerators: stars=1158, forks=229, last_commit=2025-03-25T10:14:58Z
✅ romerogroup/pyprocar: stars=190, forks=81, last_commit=2025-09-20T18:08:49Z
✅ Jean-Romain/lidR: stars=652, forks=138, last_commit=2025-10-08T18:14:57Z
✅ google-research/football: stars=3495, forks=1328, last_commit=2025-06-17T08:34:25Z
✅ drostlab/philentropy: stars=143, forks=20, last_commit=2024-12-05T13:32:58Z
✅ ContextLab/hypertools: stars=1869, forks=163, last_commit=2025-07-10T19:16:36Z
✅ lima1/PureCN: stars=140, forks=34, last_commit=2025-08-28T22:58:17Z

,Net,Woc,GH,stars,forks,last_commit_gh
620,rpatel92,Calamari-OCR_calamari,https://github.com/Calamari-OCR/calamari,1165.0,212.0,2025-05-12T16:17:04Z
621,rpatel92,pdclab_peregrine,https://github.com/pdclab/peregrine,207.0,37.0,2025-03-12T17:28:00Z
622,rpatel92,JuliaOpt_Pajarito.jl,https://github.com/JuliaOpt/Pajarito.jl,138.0,21.0,2025-04-11T08:34:36Z
623,rpatel92,MIC-DKFZ_batchgenerators,https://github.com/MIC-DKFZ/batchgenerators,1158.0,229.0,2025-03-25T10:14:58Z
624,rpatel92,romerogroup_pyprocar,https://github.com/romerogroup/pyprocar,190.0,81.0,2025-09-20T18:08:49Z
625,rpatel92,Jean-Romain_lidR,https://github.com/Jean-Romain/lidR,652.0,138.0,2025-10-08T18:14:57Z
626,rpatel92,google-research_football,https://github.com/google-research/football,3495.0,1328.0,2025-06-17T08:34:25Z
627,rpatel92,drostlab_philentropy,https://github.com/drostlab/philentropy,143.0,20.0,2024-12-05T13:32:58Z
628,rpatel92,ContextLab_hypertools,https://github.com/ContextLab/hypertools,1869.0,163.0,2025-07-10T19:16:36Z
629,rpatel92,lima1_PureCN,https://github.com/lima1/PureCN,140.0,34.0,2025-08-28T22:58:17Z

In [8]:
# Now for each of the ten projects you were assigned get commits
projects = my_projects['Woc'].tolist()  # Get the project names from 'Woc' column

list_df_commits = []  # Initialize the list

for prj in projects:
    print(f"\nFetching commits for project: {prj}")

    # Convert GitHub repository names to WoC V2412 project names
    prj_woc = prj.lower().replace('/', '_', 2)

    try:
        commits = woc.get_values('p2c', prj_woc)
        df = pd.DataFrame(commits, columns=["sha1"])
        df['project'] = prj_woc
        list_df_commits.append(df)
        print(f"  ✅ Retrieved {len(df)} commits")
    except Exception as e:
        print(f"  ⚠️ Error: {e}")

# Concatenate all commits
df = pd.concat(list_df_commits, ignore_index=True)

# Save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv', index=False)

print(f"\n✅ Total commits retrieved: {len(df)}")
df.head(1)

Fetching commits for project: Calamari-OCR_calamari
  ✅ Retrieved 833 commits

Fetching commits for project: pdclab_peregrine
  ✅ Retrieved 91 commits

Fetching commits for project: JuliaOpt_Pajarito.jl
  ✅ Retrieved 1197 commits

Fetching commits for project: MIC-DKFZ_batchgenerators
  ✅ Retrieved 730 commits

Fetching commits for project: romerogroup_pyprocar
  ✅ Retrieved 891 commits

Fetching commits for project: Jean-Romain_lidR
  ✅ Retrieved 4595 commits

Fetching commits for project: google-research_football
  ✅ Retrieved 329 commits

Fetching commits for project: drostlab_philentropy
  ✅ Retrieved 865 commits

Fetching commits for project: ContextLab_hypertools
  ✅ Retrieved 1964 commits

Fetching commits for project: lima1_PureCN
  ✅ Retrieved 1360 commits

✅ Total commits retrieved: 12855

                                       sha1                project
0  0123fe4d1694365ffacff2d0ae66b913acf5e0bb  calamari-ocr_calamari

In [9]:
# === Retrieve commit details for all commits in batches ===
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]  # Changed df_commits to df
commit_data = []

for chunk in tqdm(chunks):
    try:
        res, err = woc.get_values_many('commit.tch', chunk.to_list())
        res = {k: v[0] for k, v in res.items()}  # flatten nested list
        time.sleep(1)

        if err:
            print('Got Errors', err)

        for commit_sha, commit in res.items():
            commit_data.append({
                'commit': commit_sha,
                'tree': commit[0],
                'parent': list(commit[1]),
                'author': commit[2][0],
                'author_time': int(commit[2][1]),
                'author_tz': commit[2][2],
                'committer': commit[3][0],
                'committer_time': int(commit[3][1]),
                'committer_tz': commit[3][2],
                'message': commit[4],
            })
    except Exception as e:
        print(f"⚠️ Error retrieving batch: {e}")
        time.sleep(3)

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1', how='left')  # Changed df_commits to df
df_commit_data.to_csv('df_commit_data.csv', index=False)
print(f"\nSaved detailed commit data for {len(df_commit_data)} commits.")
df_commit_data.head(3)

  6%|▌         | 71/1286 [01:16<21:51,  1.08s/it]

Got Errors {'d9955f0a9539248fe7b6fb436f85b860caca5ddb': 'Key d9955f0a9539248fe7b6fb436f85b860caca5ddb not found in /da5_fast/All.sha1c/commit_89.tch'}

  7%|▋         | 93/1286 [01:40<21:26,  1.08s/it]

Got Errors {'01308458a81e15bd2f1fe817a3b70eb153dd694b': 'Key 01308458a81e15bd2f1fe817a3b70eb153dd694b not found in /da5_fast/All.sha1c/commit_1.tch'}

  7%|▋         | 96/1286 [01:43<21:25,  1.08s/it]

Got Errors {'06e82d48978bed3f090ff58ac822bb97b8449833': 'Key 06e82d48978bed3f090ff58ac822bb97b8449833 not found in /da5_fast/All.sha1c/commit_6.tch'}

  9%|▉         | 115/1286 [02:04<21:02,  1.08s/it]

Got Errors {'2d8bf5b831cf7532097afe0a787bfdea462c54f1': 'Key 2d8bf5b831cf7532097afe0a787bfdea462c54f1 not found in /da5_fast/All.sha1c/commit_45.tch'}

 10%|▉         | 126/1286 [02:16<20:52,  1.08s/it]

Got Errors {'464ec29cdb2fe1758133388fae76313416377a3f': 'Key 464ec29cdb2fe1758133388fae76313416377a3f not found in /da5_fast/All.sha1c/commit_70.tch'}

 12%|█▏        | 159/1286 [02:51<20:14,  1.08s/it]

Got Errors {'8dbcef63bafe7464130fa649d9dad525a6aa8c5b': 'Key 8dbcef63bafe7464130fa649d9dad525a6aa8c5b not found in /da5_fast/All.sha1c/commit_13.tch'}

 16%|█▌        | 202/1286 [03:38<19:27,  1.08s/it]

Got Errors {'e4fba1d21809e81e2d7e6756b6daee72e87cb5fd': 'Key e4fba1d21809e81e2d7e6756b6daee72e87cb5fd not found in /da5_fast/All.sha1c/commit_100.tch'}

 17%|█▋        | 213/1286 [03:49<19:15,  1.08s/it]

Got Errors {'00e7d2a010c026fb4d1e8c3fb1fa6addcbd3fff2': 'Key 00e7d2a010c026fb4d1e8c3fb1fa6addcbd3fff2 not found in /da5_fast/All.sha1c/commit_0.tch'}

 17%|█▋        | 223/1286 [04:00<19:05,  1.08s/it]

Got Errors {'28f1294fbdd93bbf87bdb5d63f4ff47a101ab8e3': 'Key 28f1294fbdd93bbf87bdb5d63f4ff47a101ab8e3 not found in /da5_fast/All.sha1c/commit_40.tch'}

 18%|█▊        | 226/1286 [04:03<19:02,  1.08s/it]

Got Errors {'332c522db2828afaaef7922cb7964458837c6305': 'Key 332c522db2828afaaef7922cb7964458837c6305 not found in /da5_fast/All.sha1c/commit_51.tch'}

 18%|█▊        | 229/1286 [04:07<18:59,  1.08s/it]

Got Errors {'3a60e177450241b0dc7ca88470a043c8c6794e9b': 'Key 3a60e177450241b0dc7ca88470a043c8c6794e9b not found in /da5_fast/All.sha1c/commit_58.tch', '3ae862967e8187a72529f6ab6445391221e660ba': 'Key 3ae862967e8187a72529f6ab6445391221e660ba not found in /da5_fast/All.sha1c/commit_58.tch'}

 20%|██        | 263/1286 [04:43<18:23,  1.08s/it]

Got Errors {'ae0f8c206692f416489ee4c0b0f016868baa1708': 'Key ae0f8c206692f416489ee4c0b0f016868baa1708 not found in /da5_fast/All.sha1c/commit_46.tch'}

 21%|██        | 265/1286 [04:45<18:20,  1.08s/it]

Got Errors {'b31259dcf2fde28a04f8c3ee6aede2c16685c6b9': 'Key b31259dcf2fde28a04f8c3ee6aede2c16685c6b9 not found in /da5_fast/All.sha1c/commit_51.tch'}

 22%|██▏       | 279/1286 [05:01<18:06,  1.08s/it]

Got Errors {'e9ce82178c78ee3a059e3aa443baeb467cfa3b41': 'Key e9ce82178c78ee3a059e3aa443baeb467cfa3b41 not found in /da5_fast/All.sha1c/commit_105.tch'}

 22%|██▏       | 288/1286 [05:10<17:55,  1.08s/it]

Got Errors {'08d3342c821a23073164b945815661dfe657f8c0': 'Key 08d3342c821a23073164b945815661dfe657f8c0 not found in /da5_fast/All.sha1c/commit_8.tch'}

 23%|██▎       | 290/1286 [05:12<17:55,  1.08s/it]

Got Errors {'10f950f522be70822066e61ec9512cb476eed7d8': 'Key 10f950f522be70822066e61ec9512cb476eed7d8 not found in /da5_fast/All.sha1c/commit_16.tch'}

 23%|██▎       | 291/1286 [05:14<17:54,  1.08s/it]

Got Errors {'12f3efbec86b8e8dc91d9087bbafc6066b6f1141': 'Key 12f3efbec86b8e8dc91d9087bbafc6066b6f1141 not found in /da5_fast/All.sha1c/commit_18.tch'}

 23%|██▎       | 293/1286 [05:16<17:51,  1.08s/it]

Got Errors {'191d31b04f86d73565a34ea4a6d686cf70a44e34': 'Key 191d31b04f86d73565a34ea4a6d686cf70a44e34 not found in /da5_fast/All.sha1c/commit_25.tch'}

 23%|██▎       | 298/1286 [05:21<17:45,  1.08s/it]

Got Errors {'26db7e3a964c35490f96b72ea3ae887e1905cdbb': 'Key 26db7e3a964c35490f96b72ea3ae887e1905cdbb not found in /da5_fast/All.sha1c/commit_38.tch'}

 23%|██▎       | 300/1286 [05:23<17:43,  1.08s/it]

Got Errors {'2ccc71d7c869720a8a6c285cdb95dcec73b3272a': 'Key 2ccc71d7c869720a8a6c285cdb95dcec73b3272a not found in /da5_fast/All.sha1c/commit_44.tch'}

 24%|██▍       | 306/1286 [05:30<17:37,  1.08s/it]

Got Errors {'438055bb300bca1bd581f9dcc82a2ba0d24d6714': 'Key 438055bb300bca1bd581f9dcc82a2ba0d24d6714 not found in /da5_fast/All.sha1c/commit_67.tch'}

 24%|██▍       | 308/1286 [05:32<17:35,  1.08s/it]

Got Errors {'46cf9e9759135dbb9a8ffb15baca9c1a45343d0b': 'Key 46cf9e9759135dbb9a8ffb15baca9c1a45343d0b not found in /da5_fast/All.sha1c/commit_70.tch'}

 24%|██▍       | 309/1286 [05:33<17:34,  1.08s/it]

Got Errors {'4b45bd86919dc345547b0e154b223d870c48021a': 'Key 4b45bd86919dc345547b0e154b223d870c48021a not found in /da5_fast/All.sha1c/commit_75.tch'}

 24%|██▍       | 311/1286 [05:35<17:31,  1.08s/it]

Got Errors {'5170fd58b9ae97210acbb33ef1401cfd0a7677a8': 'Key 5170fd58b9ae97210acbb33ef1401cfd0a7677a8 not found in /da5_fast/All.sha1c/commit_81.tch'}

 24%|██▍       | 313/1286 [05:37<17:31,  1.08s/it]

Got Errors {'554bdd11bd71db472cceff67418cff46b10df534': 'Key 554bdd11bd71db472cceff67418cff46b10df534 not found in /da5_fast/All.sha1c/commit_85.tch'}

 25%|██▍       | 320/1286 [05:45<17:22,  1.08s/it]

Got Errors {'67bc60b4343e5bca1d4f85eadb173edceccb0f8e': 'Key 67bc60b4343e5bca1d4f85eadb173edceccb0f8e not found in /da5_fast/All.sha1c/commit_103.tch', '6948aa3050b0e01237e0ddfdf724996cdc05ad66': 'Key 6948aa3050b0e01237e0ddfdf724996cdc05ad66 not found in /da5_fast/All.sha1c/commit_105.tch'}

 25%|██▍       | 321/1286 [05:46<17:22,  1.08s/it]

Got Errors {'6b47bb2ee82f033e91ad5b5b179377968745a780': 'Key 6b47bb2ee82f033e91ad5b5b179377968745a780 not found in /da5_fast/All.sha1c/commit_107.tch'}

 26%|██▌       | 329/1286 [05:55<17:10,  1.08s/it]

Got Errors {'7f3f64786c9656060cf128799f545970e7064a9d': 'Key 7f3f64786c9656060cf128799f545970e7064a9d not found in /da5_fast/All.sha1c/commit_127.tch'}

 26%|██▌       | 336/1286 [06:02<17:03,  1.08s/it]

Got Errors {'9433f9eae71e61ba01f297a989f8bbe88ac1f254': 'Key 9433f9eae71e61ba01f297a989f8bbe88ac1f254 not found in /da5_fast/All.sha1c/commit_20.tch'}

 26%|██▌       | 337/1286 [06:03<17:02,  1.08s/it]

Got Errors {'96ab7b360c0b3f39b3026ba02bebbe037054279d': 'Key 96ab7b360c0b3f39b3026ba02bebbe037054279d not found in /da5_fast/All.sha1c/commit_22.tch'}

 27%|██▋       | 346/1286 [06:13<16:54,  1.08s/it]

Got Errors {'b1ed001c1ece10034b54903383a94ecedee3d6f0': 'Key b1ed001c1ece10034b54903383a94ecedee3d6f0 not found in /da5_fast/All.sha1c/commit_49.tch'}

 27%|██▋       | 348/1286 [06:15<16:51,  1.08s/it]

Got Errors {'b960f6d074a878870d0e4067ba00e62febc84da4': 'Key b960f6d074a878870d0e4067ba00e62febc84da4 not found in /da5_fast/All.sha1c/commit_57.tch'}

 27%|██▋       | 350/1286 [06:17<16:49,  1.08s/it]

Got Errors {'bd568d4601768887d5b03a3e03fd5c3b1d22cd87': 'Key bd568d4601768887d5b03a3e03fd5c3b1d22cd87 not found in /da5_fast/All.sha1c/commit_61.tch'}

 27%|██▋       | 353/1286 [06:20<16:45,  1.08s/it]

Got Errors {'c5254d6e95f1fe2d583a8e55a72d79f0d11d1074': 'Key c5254d6e95f1fe2d583a8e55a72d79f0d11d1074 not found in /da5_fast/All.sha1c/commit_69.tch'}

 28%|██▊       | 354/1286 [06:22<16:44,  1.08s/it]

Got Errors {'c6b13b8392283b9c7b2344320c3ac0f3795b0d25': 'Key c6b13b8392283b9c7b2344320c3ac0f3795b0d25 not found in /da5_fast/All.sha1c/commit_70.tch'}

 28%|██▊       | 356/1286 [06:24<16:42,  1.08s/it]

Got Errors {'cc559242a7757727f20104c766dd5bd26d0e0572': 'Key cc559242a7757727f20104c766dd5bd26d0e0572 not found in /da5_fast/All.sha1c/commit_76.tch', 'cd07437d2591647c67149f2a62dcca058ae241bf': 'Key cd07437d2591647c67149f2a62dcca058ae241bf not found in /da5_fast/All.sha1c/commit_77.tch'}

 28%|██▊       | 358/1286 [06:26<16:40,  1.08s/it]

Got Errors {'d1aa9c8ce1244d573f425d82b234e3840dc5bfb1': 'Key d1aa9c8ce1244d573f425d82b234e3840dc5bfb1 not found in /da5_fast/All.sha1c/commit_81.tch'}

 28%|██▊       | 359/1286 [06:27<16:38,  1.08s/it]

Got Errors {'d458299d50ce5456acb6780d2889cdf6fa1fff61': 'Key d458299d50ce5456acb6780d2889cdf6fa1fff61 not found in /da5_fast/All.sha1c/commit_84.tch'}

 28%|██▊       | 360/1286 [06:28<16:37,  1.08s/it]

Got Errors {'d5123b713d352ddaffc7fd0369a64a293c39204f': 'Key d5123b713d352ddaffc7fd0369a64a293c39204f not found in /da5_fast/All.sha1c/commit_85.tch', 'd56dc84e77ad99d72e903bd1afce6cd0a1a8b72b': 'Key d56dc84e77ad99d72e903bd1afce6cd0a1a8b72b not found in /da5_fast/All.sha1c/commit_85.tch'}

 28%|██▊       | 365/1286 [06:33<16:32,  1.08s/it]

Got Errors {'e1af5a7e8dae5771fe2eec552c9d559eaee210c1': 'Key e1af5a7e8dae5771fe2eec552c9d559eaee210c1 not found in /da5_fast/All.sha1c/commit_97.tch'}

 29%|██▊       | 368/1286 [06:37<16:29,  1.08s/it]

Got Errors {'ed522c3fdfe410d2aadc891a6da8f546c342229f': 'Key ed522c3fdfe410d2aadc891a6da8f546c342229f not found in /da5_fast/All.sha1c/commit_109.tch'}

 29%|██▉       | 370/1286 [06:39<16:28,  1.08s/it]

Got Errors {'f2a0294d485c666ed29f40d075d04545494f5132': 'Key f2a0294d485c666ed29f40d075d04545494f5132 not found in /da5_fast/All.sha1c/commit_114.tch'}

 29%|██▉       | 371/1286 [06:40<16:26,  1.08s/it]

Got Errors {'f63f2488e687ff69122aab5b4036cbb25dc37759': 'Key f63f2488e687ff69122aab5b4036cbb25dc37759 not found in /da5_fast/All.sha1c/commit_118.tch'}

100%|██████████| 1286/1286 [23:07<00:00,  1.08s/it]

Saved detailed commit data for 12808 commits.

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,0123fe4d1694365ffacff2d0ae66b913acf5e0bb,5d61ae325d2faa67e821c444d50ddf083701d138,[6e5d92ad755ca34379752c54da5326ba6ef5c6d8],Christoph Wick <wick.chr.info@gmail.com>,1536677973,+0200,Christoph Wick <wick.chr.info@gmail.com>,1536677973,+0200,added support for abbyy.xml files as input (ne...,0123fe4d1694365ffacff2d0ae66b913acf5e0bb,calamari-ocr_calamari
1,017766a18c260883f87747dfd3ee061dd36179d7,970959e781b1aa842752600c3e27544f06d8f8b4,[1da5d4df5938ea596caeab86afea8ef822793f37],Christoph Wick <wick.chr.info@gmail.com>,1571820729,+0200,Christoph Wick <wick.chr.info@gmail.com>,1571820729,+0200,Ignoring NaN as CER in early stopping\n,017766a18c260883f87747dfd3ee061dd36179d7,calamari-ocr_calamari
2,02d46bf03a7371beae462e41f6f5b6d42151566c,8f90c8adadd723d226b369b60e37b0e148501882,[798aed6afd033d27e9bc2f25b003b4a781ff2bf7],Christoph Wick <wick.chr.info@gmail.com>,1571995296,+0200,Christoph Wick <wick.chr.info@gmail.com>,1572008416,+0200,Added training callback to allow external prog...,02d46bf03a7371beae462e41f6f5b6d42151566c,calamari-ocr_calamari

In [10]:
# === Create the final project summary CSV ===
df_summary = df_commit_data[['project', 'commit', 'author', 'author_time', 'message']].copy()
df_summary.rename(columns={'author_time': 'time'}, inplace=True)

summary_file = f"{NETID}_project_summary.csv"
df_summary.to_csv(summary_file, sep=';', index=False)

print(f"✅ Saved summary CSV: {summary_file}")
df_summary.head(3)

✅ Saved summary CSV: rpatel92_project_summary.csv

,project,commit,author,time,message
0,calamari-ocr_calamari,0123fe4d1694365ffacff2d0ae66b913acf5e0bb,Christoph Wick <wick.chr.info@gmail.com>,1536677973,added support for abbyy.xml files as input (ne...
1,calamari-ocr_calamari,017766a18c260883f87747dfd3ee061dd36179d7,Christoph Wick <wick.chr.info@gmail.com>,1571820729,Ignoring NaN as CER in early stopping\n
2,calamari-ocr_calamari,02d46bf03a7371beae462e41f6f5b6d42151566c,Christoph Wick <wick.chr.info@gmail.com>,1571995296,Added training callback to allow external prog...